// Generated by clj-compile from <embedded>/clojure/template.clj; do not edit.
#include "compiled_internal.h"

#define FILE_STR (K[0])
#ifdef CLJ_COMPILED_CORE
static clj_value K[15];
static clj_value V[19];
static clj_value B[3];
static const clj_intrinsic *OP[3];
static const clj_fusion_var *F[1];
static clj_node S[3];
static void unit_pools(void);

static clj_value top_0(void);
static clj_value top_1(void);
static clj_value top_2(void);
static clj_value top_3(void);
static clj_value top_4(void);
clj_value clojure_template_apply_template_a3(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs);
static clj_value clojure_template_apply_template(void *ctx, const clj_value *args, size_t n);
static clj_value top_5(void);
clj_value clojure_template_do_template_v4(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs);
static clj_value clojure_template_do_template__0_a1(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs);
static clj_value clojure_template_do_template__0(void *ctx, const clj_value *args, size_t n);
static clj_value clojure_template_do_template(void *ctx, const clj_value *args, size_t n);

#ifdef CLJ_CLOSED
#define CLJC_DIRECT_clojure_core_every_QMARK__a2 1
static clj_compiled_fn CLJC_FN_clojure_core_every_QMARK__a2;
#define CLJC_DIRECT_clojure_core_zipmap_a2 1
static clj_compiled_fn CLJC_FN_clojure_core_zipmap_a2;
#define CLJC_DIRECT_clojure_walk_postwalk_replace_a2 1
static clj_compiled_fn CLJC_FN_clojure_walk_postwalk_replace_a2;
#define CLJC_LOCAL_clojure_template_apply_template_a3 1
#define CLJC_CALL_clojure_template_apply_template_a3 clojure_template_apply_template_a3
#define CLJC_DIRECT_clojure_core_partition_a2 1
static clj_compiled_fn CLJC_FN_clojure_core_partition_a2;
#define CLJC_DIRECT_clojure_core_map_a2 1
static clj_compiled_fn CLJC_FN_clojure_core_map_a2;
#define CLJC_DIRECT_clojure_core_concat_a2 1
static clj_compiled_fn CLJC_FN_clojure_core_concat_a2;
#endif

static clj_value top_0(void) {
	clj_cframe fr = {NULL, NULL, 0, NULL};
	(void)fr;
	clj_eval_top_enter();
#line 3 "<embedded>/clojure/template.clj"
	clj_value t0;
	bool o1;
	clj_value t1 = clj_c_var_borrow(V[0], &o1);
	if (t1 == CLJ_THROWN) {
	goto L1;
	}
	clj_value t2 = K[1];
	clj_value a0[1] = {t2};
	(void)a0;
	t0 = clj_c_invoke(t1, a0, 1);
	(void)t2;
	if (o1) clj_release(t1);
	if (t0 == CLJ_THROWN) {
	goto L1;
	}
	clj_eval_top_leave();
	return t0;
L1: ;
	clj_eval_top_leave();
	return CLJ_THROWN;
}

static clj_value top_1(void) {
	clj_cframe fr = {NULL, NULL, 0, NULL};
	(void)fr;
	clj_eval_top_enter();
#line 3 "<embedded>/clojure/template.clj"
	clj_value t0;
	bool o1;
	clj_value t1 = clj_c_var_borrow(V[1], &o1);
	if (t1 == CLJ_THROWN) {
	goto L1;
	}
	const clj_value *a0 = NULL;
	t0 = clj_c_invoke(t1, a0, 0);
	if (o1) clj_release(t1);
	if (t0 == CLJ_THROWN) {
	goto L1;
	}
	clj_eval_top_leave();
	return t0;
L1: ;
	clj_eval_top_leave();
	return CLJ_THROWN;
}

static clj_value top_2(void) {
	clj_cframe fr = {NULL, NULL, 0, NULL};
	(void)fr;
	clj_eval_top_enter();
#line 3 "<embedded>/clojure/template.clj"
	clj_value t0;
	bool o1;
	clj_value t1 = clj_c_var_borrow(V[2], &o1);
	if (t1 == CLJ_THROWN) {
	goto L1;
	}
	clj_value t2 = K[2];
	clj_value a0[1] = {t2};
	(void)a0;
	t0 = clj_c_invoke(t1, a0, 1);
	(void)t2;
	if (o1) clj_release(t1);
	if (t0 == CLJ_THROWN) {
	goto L1;
	}
	clj_eval_top_leave();
	return t0;
L1: ;
	clj_eval_top_leave();
	return CLJ_THROWN;
}

static clj_value top_3(void) {
	clj_cframe fr = {NULL, NULL, 0, NULL};
	(void)fr;
	clj_eval_top_enter();
#line 3 "<embedded>/clojure/template.clj"
	clj_value t0 = clj_retain(K[3]);
	clj_eval_top_leave();
	return t0;
}

CLJC_FRAME clj_value clojure_template_apply_template_a3(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs) {
	(void)self; (void)captured; (void)args; (void)nargs;
	clj_cframe fr = {NULL, captured, 0, NULL};
	(void)fr;
	clj_value l0 = args[0];
	(void)l0;
	clj_value l1 = args[1];
	(void)l1;
	clj_value l2 = args[2];
	(void)l2;
	clj_ccall cc;
	CLJC_ENTER(&S[0], &cc);
#line 6 "<embedded>/clojure/template.clj"
#line 10 "<embedded>/clojure/template.clj"
	clj_value t0 = l0;
	clj_value a0[1] = {t0};
	(void)a0;
	clj_value t1;
	if (CLJC_GUARD(V[4], B[0])) {
	t1 = clj_vector_p(t0);
	} else {
	t1 = clj_c_intrinsic_fallback(V[4], a0, 1);
	}
	(void)t0;
	CLJC_SITE(&S[0]);
	if (t1 == CLJ_THROWN) {
	goto L1;
	}
	bool t2 = clj_truthy(t1);
	clj_release(t1);
	clj_value t3;
	if (t2) {
	clj_value t4 = clj_retain(K[3]);
	t3 = t4;
	} else {
	clj_value t5;
	bool o6;
	clj_value t6 = clj_c_var_borrow(V[5], &o6);
	CLJC_SITE(&S[0]);
	if (t6 == CLJ_THROWN) {
	goto L1;
	}
	clj_value t7;
	bool o8;
	clj_value t8 = clj_c_var_borrow(V[6], &o8);
	CLJC_SITE(&S[0]);
	if (t8 == CLJ_THROWN) {
	if (o6) clj_release(t6);
	goto L1;
	}
	clj_value t9 = K[6];
	clj_value t10;
	bool o11;
	clj_value t11 = clj_c_var_borrow(V[7], &o11);
	CLJC_SITE(&S[0]);
	if (t11 == CLJ_THROWN) {
	if (o8) clj_release(t8);
	if (o6) clj_release(t6);
	goto L1;
	}
	clj_value t12 = K[7];
	clj_value a3[1] = {t12};
	(void)a3;
	t10 = clj_c_invoke(t11, a3, 1);
	(void)t12;
	if (o11) clj_release(t11);
	CLJC_SITE(&S[0]);
	if (t10 == CLJ_THROWN) {
	if (o8) clj_release(t8);
	if (o6) clj_release(t6);
	goto L1;
	}
	clj_value a2[2] = {t9, t10};
	(void)a2;
	t7 = clj_c_invoke(t8, a2, 2);
	clj_release(t10);
	(void)t9;
	if (o8) clj_release(t8);
	CLJC_SITE(&S[0]);
	if (t7 == CLJ_THROWN) {
	if (o6) clj_release(t6);
	goto L1;
	}
	clj_value t13 = K[8];
	clj_value a1[2] = {t7, t13};
	(void)a1;
	t5 = clj_c_invoke(t6, a1, 2);
	(void)t13;
	clj_release(t7);
	if (o6) clj_release(t6);
	CLJC_SITE(&S[0]);
	if (t5 == CLJ_THROWN) {
	goto L1;
	}
	clj_value t14 = clj_throw(t5);
	CLJC_SITE(&S[0]);
	if (t14 == CLJ_THROWN) {
	goto L1;
	}
	t3 = t14;
	}
	clj_release(t3);
#line 11 "<embedded>/clojure/template.clj"
	clj_value t15;
	bool o16 = false;
	clj_value t16 = CLJ_NIL;
#ifndef CLJC_LOCAL_clojure_core_every_QMARK__a2
	t16 = clj_c_var_borrow(V[8], &o16);
	CLJC_SITE(&S[0]);
	if (t16 == CLJ_THROWN) {
	goto L1;
	}
#endif
	bool o17;
	clj_value t17 = clj_c_var_borrow(V[9], &o17);
	CLJC_SITE(&S[0]);
	if (t17 == CLJ_THROWN) {
	if (o16) clj_release(t16);
	goto L1;
	}
	clj_value t18 = l0;
	clj_value a4[2] = {t17, t18};
	(void)a4;
#ifdef CLJC_LOCAL_clojure_core_every_QMARK__a2
	t15 = CLJC_CALL_clojure_core_every_QMARK__a2(CLJ_NIL, NULL, a4, 2);
#elif defined(CLJC_DIRECT_clojure_core_every_QMARK__a2)
	if (!CLJC_FN_clojure_core_every_QMARK__a2) CLJC_FN_clojure_core_every_QMARK__a2 = clj_compiled_symbol("clojure_core_every_QMARK__a2");
	t15 = CLJC_FN_clojure_core_every_QMARK__a2 ? CLJC_FN_clojure_core_every_QMARK__a2(clj_var_root_relaxed(V[8]), NULL, a4, 2) : clj_c_invoke(t16, a4, 2);
#else
	t15 = clj_c_invoke(t16, a4, 2);
#endif
	(void)t18;
	if (o17) clj_release(t17);
	if (o16) clj_release(t16);
	CLJC_SITE(&S[0]);
	if (t15 == CLJ_THROWN) {
	goto L1;
	}
	bool t19 = clj_truthy(t15);
	clj_release(t15);
	clj_value t20;
	if (t19) {
	clj_value t21 = clj_retain(K[3]);
	t20 = t21;
	} else {
	clj_value t22;
	bool o23;
	clj_value t23 = clj_c_var_borrow(V[5], &o23);
	CLJC_SITE(&S[0]);
	if (t23 == CLJ_THROWN) {
	goto L1;
	}
	clj_value t24;
	bool o25;
	clj_value t25 = clj_c_var_borrow(V[6], &o25);
	CLJC_SITE(&S[0]);
	if (t25 == CLJ_THROWN) {
	if (o23) clj_release(t23);
	goto L1;
	}
	clj_value t26 = K[6];
	clj_value t27;
	bool o28;
	clj_value t28 = clj_c_var_borrow(V[7], &o28);
	CLJC_SITE(&S[0]);
	if (t28 == CLJ_THROWN) {
	if (o25) clj_release(t25);
	if (o23) clj_release(t23);
	goto L1;
	}
	clj_value t29 = K[9];
	clj_value a7[1] = {t29};
	(void)a7;
	t27 = clj_c_invoke(t28, a7, 1);
	(void)t29;
	if (o28) clj_release(t28);
	CLJC_SITE(&S[0]);
	if (t27 == CLJ_THROWN) {
	if (o25) clj_release(t25);
	if (o23) clj_release(t23);
	goto L1;
	}
	clj_value a6[2] = {t26, t27};
	(void)a6;
	t24 = clj_c_invoke(t25, a6, 2);
	clj_release(t27);
	(void)t26;
	if (o25) clj_release(t25);
	CLJC_SITE(&S[0]);
	if (t24 == CLJ_THROWN) {
	if (o23) clj_release(t23);
	goto L1;
	}
	clj_value t30 = K[8];
	clj_value a5[2] = {t24, t30};
	(void)a5;
	t22 = clj_c_invoke(t23, a5, 2);
	(void)t30;
	clj_release(t24);
	if (o23) clj_release(t23);
	CLJC_SITE(&S[0]);
	if (t22 == CLJ_THROWN) {
	goto L1;
	}
	clj_value t31 = clj_throw(t22);
	CLJC_SITE(&S[0]);
	if (t31 == CLJ_THROWN) {
	goto L1;
	}
	t20 = t31;
	}
	clj_release(t20);
#line 12 "<embedded>/clojure/template.clj"
	clj_value t32;
	bool o33 = false;
	clj_value t33 = CLJ_NIL;
#ifndef CLJC_LOCAL_clojure_walk_postwalk_replace_a2
	t33 = clj_c_var_borrow(V[10], &o33);
	CLJC_SITE(&S[0]);
	if (t33 == CLJ_THROWN) {
	goto L1;
	}
#endif
	clj_value t34;
	bool o35 = false;
	clj_value t35 = CLJ_NIL;
#ifndef CLJC_LOCAL_clojure_core_zipmap_a2
	t35 = clj_c_var_borrow(V[11], &o35);
	CLJC_SITE(&S[0]);
	if (t35 == CLJ_THROWN) {
	if (o33) clj_release(t33);
	goto L1;
	}
#endif
	clj_value t36 = l0;
	clj_value t37 = l2;
	clj_value a9[2] = {t36, t37};
	(void)a9;
#ifdef CLJC_LOCAL_clojure_core_zipmap_a2
	t34 = CLJC_CALL_clojure_core_zipmap_a2(CLJ_NIL, NULL, a9, 2);
#elif defined(CLJC_DIRECT_clojure_core_zipmap_a2)
	if (!CLJC_FN_clojure_core_zipmap_a2) CLJC_FN_clojure_core_zipmap_a2 = clj_compiled_symbol("clojure_core_zipmap_a2");
	t34 = CLJC_FN_clojure_core_zipmap_a2 ? CLJC_FN_clojure_core_zipmap_a2(clj_var_root_relaxed(V[11]), NULL, a9, 2) : clj_c_invoke(t35, a9, 2);
#else
	t34 = clj_c_invoke(t35, a9, 2);
#endif
	(void)t37;
	(void)t36;
	if (o35) clj_release(t35);
	CLJC_SITE(&S[0]);
	if (t34 == CLJ_THROWN) {
	if (o33) clj_release(t33);
	goto L1;
	}
	clj_value t38 = l1;
	clj_value a8[2] = {t34, t38};
	(void)a8;
#ifdef CLJC_LOCAL_clojure_walk_postwalk_replace_a2
	t32 = CLJC_CALL_clojure_walk_postwalk_replace_a2(CLJ_NIL, NULL, a8, 2);
#elif defined(CLJC_DIRECT_clojure_walk_postwalk_replace_a2)
	if (!CLJC_FN_clojure_walk_postwalk_replace_a2) CLJC_FN_clojure_walk_postwalk_replace_a2 = clj_compiled_symbol("clojure_walk_postwalk_replace_a2");
	t32 = CLJC_FN_clojure_walk_postwalk_replace_a2 ? CLJC_FN_clojure_walk_postwalk_replace_a2(clj_var_root_relaxed(V[10]), NULL, a8, 2) : clj_c_invoke(t33, a8, 2);
#else
	t32 = clj_c_invoke(t33, a8, 2);
#endif
	(void)t38;
	clj_release(t34);
	if (o33) clj_release(t33);
	CLJC_SITE(&S[0]);
	if (t32 == CLJ_THROWN) {
	goto L1;
	}
	CLJC_LEAVE(&S[0], &cc);
	return t32;
L1: ;
	CLJC_LEAVE(&S[0], &cc);
	return CLJ_THROWN;
}

static clj_value clojure_template_apply_template(void *ctx, const clj_value *args, size_t n) {
	const clj_fn *f = ctx;
	switch (n) {
	case 3: return clojure_template_apply_template_a3(clj_from_ptr((void *)f), f->env, args, n);
	default: break;
	}
	return clj_c_arity_error(clj_from_ptr((void *)f), n);
}

static clj_value top_4(void) {
	clj_cframe fr = {NULL, NULL, 0, NULL};
	(void)fr;
	clj_eval_top_enter();
#line 6 "<embedded>/clojure/template.clj"
	clj_value t0 = clj_c_closure(K[5], clojure_template_apply_template, NULL, 0, 0x8, 3, 3);
	clj_var_bind_root(V[3], t0);
	clj_release(t0);
	clj_value t1 = clj_retain(K[10]);
	clj_value t2 = clj_c_def(V[3], t1, false, false);
	clj_release(t1);
	if (t2 == CLJ_THROWN) {
	goto L1;
	}
	clj_eval_top_leave();
	return t2;
L1: ;
	clj_eval_top_leave();
	return CLJ_THROWN;
}

static CLJC_FRAME clj_value clojure_template_do_template__0_a1(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs) {
	(void)self; (void)captured; (void)args; (void)nargs;
	clj_cframe fr = {NULL, captured, 0, NULL};
	(void)fr;
	clj_value l0 = args[0];
	(void)l0;
	clj_ccall cc;
	CLJC_ENTER(&S[2], &cc);
#line 18 "<embedded>/clojure/template.clj"
	clj_value t0;
	bool o1 = false;
	clj_value t1 = CLJ_NIL;
#ifndef CLJC_LOCAL_clojure_template_apply_template_a3
	t1 = clj_c_var_borrow(V[3], &o1);
	CLJC_SITE(&S[2]);
	if (t1 == CLJ_THROWN) {
	goto L1;
	}
#endif
	clj_value t2 = fr.captured[0];
	clj_value t3 = fr.captured[1];
	clj_value t4 = l0;
	clj_value a0[3] = {t2, t3, t4};
	(void)a0;
#ifdef CLJC_LOCAL_clojure_template_apply_template_a3
	t0 = CLJC_CALL_clojure_template_apply_template_a3(CLJ_NIL, NULL, a0, 3);
#elif defined(CLJC_DIRECT_clojure_template_apply_template_a3)
	if (!CLJC_FN_clojure_template_apply_template_a3) CLJC_FN_clojure_template_apply_template_a3 = clj_compiled_symbol("clojure_template_apply_template_a3");
	t0 = CLJC_FN_clojure_template_apply_template_a3 ? CLJC_FN_clojure_template_apply_template_a3(clj_var_root_relaxed(V[3]), NULL, a0, 3) : clj_c_invoke(t1, a0, 3);
#else
	t0 = clj_c_invoke(t1, a0, 3);
#endif
	(void)t4;
	(void)t3;
	(void)t2;
	if (o1) clj_release(t1);
	CLJC_SITE(&S[2]);
	if (t0 == CLJ_THROWN) {
	goto L1;
	}
	CLJC_LEAVE(&S[2], &cc);
	return t0;
L1: ;
	CLJC_LEAVE(&S[2], &cc);
	return CLJ_THROWN;
}

static clj_value clojure_template_do_template__0(void *ctx, const clj_value *args, size_t n) {
	const clj_fn *f = ctx;
	switch (n) {
	case 1: return clojure_template_do_template__0_a1(clj_from_ptr((void *)f), f->env, args, n);
	default: break;
	}
	return clj_c_arity_error(clj_from_ptr((void *)f), n);
}

CLJC_FRAME clj_value clojure_template_do_template_v4(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs) {
	(void)self; (void)captured; (void)args; (void)nargs;
	clj_value s[4];
	clj_cframe fr = {s, captured, 0, NULL};
	(void)fr;
	clj_value l0 = args[0];
	(void)l0;
	clj_value l1 = args[1];
	(void)l1;
	s[2] = args[2];
	s[3] = args[3];
	clj_value l4 = CLJ_NIL;
	clj_value l5 = CLJ_NIL;
	l4 = nargs > 4 ? clj_list_from_array(args + 4, nargs - 4) : CLJ_NIL;
	clj_ccall cc;
	CLJC_ENTER(&S[1], &cc);
#line 17 "<embedded>/clojure/template.clj"
	clj_value t0 = fr.slots[2];
	clj_value a0[1] = {t0};
	(void)a0;
	clj_value t1;
	if (CLJC_GUARD(V[13], B[1])) {
	t1 = clj_count(t0);
	} else {
	t1 = clj_c_intrinsic_fallback(V[13], a0, 1);
	}
	(void)t0;
	CLJC_SITE(&S[1]);
	if (t1 == CLJ_THROWN) {
	goto L1;
	}
	clj_c_rebind(&l5, t1);
	clj_value t2;
	bool o3 = false;
	clj_value t3 = CLJ_NIL;
#ifndef CLJC_LOCAL_clojure_core_concat_a2
	t3 = clj_c_var_borrow(V[15], &o3);
	CLJC_SITE(&S[1]);
	if (t3 == CLJ_THROWN) {
	goto L1;
	}
#endif
	clj_value t4;
	bool o5;
	clj_value t5 = clj_c_var_borrow(V[16], &o5);
	CLJC_SITE(&S[1]);
	if (t5 == CLJ_THROWN) {
	if (o3) clj_release(t3);
	goto L1;
	}
	clj_value t6 = K[13];
	clj_value a3[1] = {t6};
	(void)a3;
	t4 = clj_c_invoke(t5, a3, 1);
	(void)t6;
	if (o5) clj_release(t5);
	CLJC_SITE(&S[1]);
	if (t4 == CLJ_THROWN) {
	if (o3) clj_release(t3);
	goto L1;
	}
#line 18 "<embedded>/clojure/template.clj"
	clj_value t7;
	bool o8 = false;
	clj_value t8 = CLJ_NIL;
#ifndef CLJC_LOCAL_clojure_core_map_a2
	t8 = clj_c_var_borrow(V[17], &o8);
	CLJC_SITE(&S[1]);
	if (t8 == CLJ_THROWN) {
	clj_release(t4);
	if (o3) clj_release(t3);
	goto L1;
	}
#endif
	clj_value c5[2] = {fr.slots[2], fr.slots[3]};
	clj_value t9 = clj_c_closure(CLJ_NIL, clojure_template_do_template__0, c5, 2, 0x2, 1, 1);
	clj_value t10;
	bool o11 = false;
	clj_value t11 = CLJ_NIL;
#ifndef CLJC_LOCAL_clojure_core_partition_a2
	t11 = clj_c_var_borrow(V[18], &o11);
	CLJC_SITE(&S[1]);
	if (t11 == CLJ_THROWN) {
	clj_release(t9);
	if (o8) clj_release(t8);
	clj_release(t4);
	if (o3) clj_release(t3);
	goto L1;
	}
#endif
	clj_value t12 = l5;
	clj_value t13 = l4;
	clj_value a6[2] = {t12, t13};
	(void)a6;
#ifdef CLJC_LOCAL_clojure_core_partition_a2
	t10 = CLJC_CALL_clojure_core_partition_a2(CLJ_NIL, NULL, a6, 2);
#elif defined(CLJC_DIRECT_clojure_core_partition_a2)
	if (!CLJC_FN_clojure_core_partition_a2) CLJC_FN_clojure_core_partition_a2 = clj_compiled_symbol("clojure_core_partition_a2");
	t10 = CLJC_FN_clojure_core_partition_a2 ? CLJC_FN_clojure_core_partition_a2(clj_var_root_relaxed(V[18]), NULL, a6, 2) : clj_c_invoke(t11, a6, 2);
#else
	t10 = clj_c_invoke(t11, a6, 2);
#endif
	(void)t13;
	(void)t12;
	if (o11) clj_release(t11);
	CLJC_SITE(&S[1]);
	if (t10 == CLJ_THROWN) {
	clj_release(t9);
	if (o8) clj_release(t8);
	clj_release(t4);
	if (o3) clj_release(t3);
	goto L1;
	}
	clj_value a4[2] = {t9, t10};
	(void)a4;
#ifdef CLJC_LOCAL_clojure_core_map_a2
	t7 = CLJC_CALL_clojure_core_map_a2(CLJ_NIL, NULL, a4, 2);
#elif defined(CLJC_DIRECT_clojure_core_map_a2)
	if (!CLJC_FN_clojure_core_map_a2) CLJC_FN_clojure_core_map_a2 = clj_compiled_symbol("clojure_core_map_a2");
	t7 = CLJC_FN_clojure_core_map_a2 ? CLJC_FN_clojure_core_map_a2(clj_var_root_relaxed(V[17]), NULL, a4, 2) : clj_c_invoke(t8, a4, 2);
#else
	t7 = clj_c_invoke(t8, a4, 2);
#endif
	clj_release(t10);
	clj_release(t9);
	if (o8) clj_release(t8);
	CLJC_SITE(&S[1]);
	if (t7 == CLJ_THROWN) {
	clj_release(t4);
	if (o3) clj_release(t3);
	goto L1;
	}
	clj_value a2[2] = {t4, t7};
	(void)a2;
#ifdef CLJC_LOCAL_clojure_core_concat_a2
	t2 = CLJC_CALL_clojure_core_concat_a2(clj_var_root_relaxed(V[15]), NULL, a2, 2);
#elif defined(CLJC_DIRECT_clojure_core_concat_a2)
	if (!CLJC_FN_clojure_core_concat_a2) CLJC_FN_clojure_core_concat_a2 = clj_compiled_symbol("clojure_core_concat_a2");
	t2 = CLJC_FN_clojure_core_concat_a2 ? CLJC_FN_clojure_core_concat_a2(clj_var_root_relaxed(V[15]), NULL, a2, 2) : clj_c_invoke(t3, a2, 2);
#else
	t2 = clj_c_invoke(t3, a2, 2);
#endif
	clj_release(t7);
	clj_release(t4);
	if (o3) clj_release(t3);
	CLJC_SITE(&S[1]);
	if (t2 == CLJ_THROWN) {
	goto L1;
	}
	clj_value a1[1] = {t2};
	(void)a1;
	clj_value t14;
	if (CLJC_GUARD(V[14], B[2])) {
	t14 = clj_seq(t2);
	} else {
	t14 = clj_c_intrinsic_fallback(V[14], a1, 1);
	}
	clj_release(t2);
	CLJC_SITE(&S[1]);
	if (t14 == CLJ_THROWN) {
	goto L1;
	}
	CLJC_LEAVE(&S[1], &cc);
	clj_release(l4);
	clj_release(l5);
	clj_c_release_slots(&fr, 4);
	return t14;
L1: ;
	CLJC_LEAVE(&S[1], &cc);
	clj_release(l4);
	clj_release(l5);
	clj_c_release_slots(&fr, 4);
	return CLJ_THROWN;
}

static clj_value clojure_template_do_template(void *ctx, const clj_value *args, size_t n) {
	const clj_fn *f = ctx;
	switch (n) {
	default: break;
	}
	if (n >= 4) return clojure_template_do_template_v4(clj_from_ptr((void *)f), f->env, args, n);
	return clj_c_arity_error(clj_from_ptr((void *)f), n);
}

static clj_value top_5(void) {
	clj_cframe fr = {NULL, NULL, 0, NULL};
	(void)fr;
	clj_eval_top_enter();
#line 14 "<embedded>/clojure/template.clj"
	clj_value t0 = clj_c_closure(K[12], clojure_template_do_template, NULL, 0, 0x0, 4, CLJ_ARITY_ANY);
	clj_var_bind_root(V[12], t0);
	clj_release(t0);
	clj_value t1 = clj_retain(K[14]);
	clj_value t2 = clj_c_def(V[12], t1, true, false);
	clj_release(t1);
	if (t2 == CLJ_THROWN) {
	goto L1;
	}
	clj_eval_top_leave();
	return t2;
L1: ;
	clj_eval_top_leave();
	return CLJ_THROWN;
}

static const clj_frame_entry FR[3] = {
	{(clj_code)clojure_template_apply_template_a3, &S[0]},
	{(clj_code)clojure_template_do_template_v4, &S[1]},
	{(clj_code)clojure_template_do_template__0_a1, &S[2]},
};

static bool pools_filled;

static void unit_pools(void) {
	(void)K; (void)V; (void)B; (void)OP; (void)F; (void)S;
	pools_filled = true;
	clj_c_register_frames(FR, 3);
	V[0] = clj_c_var("clojure.core", "in-ns");
	V[1] = clj_c_var("clojure.core", "refer-clojure");
	V[2] = clj_c_var("clojure.core", "require");
	V[3] = clj_c_var("clojure.template", "apply-template");
	V[4] = clj_c_var("clojure.core", "vector?");
	V[5] = clj_c_var("clojure.core", "ex-info");
	V[6] = clj_c_var("clojure.core", "str");
	V[7] = clj_c_var("clojure.core", "pr-str");
	V[8] = clj_c_var("clojure.core", "every?");
	V[9] = clj_c_var("clojure.core", "symbol?");
	V[10] = clj_c_var("clojure.walk", "postwalk-replace");
	V[11] = clj_c_var("clojure.core", "zipmap");
	V[12] = clj_c_var("clojure.template", "do-template");
	V[13] = clj_c_var("clojure.core", "count");
	V[14] = clj_c_var("clojure.core", "seq");
	V[15] = clj_c_var("clojure.core", "concat");
	V[16] = clj_c_var("clojure.core", "list");
	V[17] = clj_c_var("clojure.core", "map");
	V[18] = clj_c_var("clojure.core", "partition");
	K[0] = clj_c_const("\"<embedded>/clojure/template.clj\"", 33);
	K[1] = clj_c_const("clojure.template", 16);
	K[2] = clj_c_const("[clojure.walk :as walk]", 23);
	K[3] = clj_c_const("nil", 3);
	K[4] = clj_c_const("apply-template", 14);
	K[5] = clj_c_const("clojure.template/apply-template", 31);
	K[6] = clj_c_const("\"Assert failed: \"", 17);
	K[7] = clj_c_const("(vector? argv)", 14);
	K[8] = clj_c_const("{}", 2);
	K[9] = clj_c_const("(every? symbol? argv)", 21);
	K[10] = clj_c_const("{:ns clojure.template, :file \"<embedded>/clojure/template.clj\", :arglists ([argv expr values]), :doc \"For use in macros. argv is an argument list as in defn; expr is a quoted expression using the\\n  symbols in argv; values is a sequence of values for them. Returns expr with the values substituted.\", :name apply-template, :line 6, :column 1}", 342);
	K[11] = clj_c_const("do-template", 11);
	K[12] = clj_c_const("clojure.template/do-template", 28);
	K[13] = clj_c_const("do", 2);
	K[14] = clj_c_const("{:ns clojure.template, :file \"<embedded>/clojure/template.clj\", :arglists ([argv expr & values]), :macro true, :doc \"Repeatedly copies expr (in a do block) for each group of arguments in values, substituting them for argv.\", :name do-template, :line 14, :column 1}", 264);
	OP[0] = clj_c_intrinsic("clojure.core/vector?", 1);
	B[0] = clj_intrinsic_builtin(OP[0]);
	OP[1] = clj_c_intrinsic("clojure.core/count", 1);
	B[1] = clj_intrinsic_builtin(OP[1]);
	OP[2] = clj_c_intrinsic("clojure.core/seq", 1);
	B[2] = clj_intrinsic_builtin(OP[2]);
}

clj_value clj_compiled_lib_init_clojure_template(void) {
	clj_value r;
	(void)r;
	if (!pools_filled) unit_pools();
#ifdef CLJ_CLOSED
	clj_compiled_register_symbol("clojure_template_apply_template_a3", clojure_template_apply_template_a3);
#endif
	// form 1 at 3:1
	if (0) {
F1: ;
	if (!clj_load_form_failed(FILE_STR, 3, 1, CLJ_NIL)) goto fail;
	goto N1;
	}
	r = top_0();
	if (r == CLJ_THROWN) goto F1;
	clj_release(r);
	r = top_1();
	if (r == CLJ_THROWN) goto F1;
	clj_release(r);
	r = top_2();
	if (r == CLJ_THROWN) goto F1;
	clj_release(r);
	r = top_3();
	if (r == CLJ_THROWN) goto F1;
	clj_release(r);
N1: ;
	// form 2 at 6:1
	if (0) {
F2: ;
	if (!clj_load_form_failed(FILE_STR, 6, 1, K[4])) goto fail;
	goto N2;
	}
	clj_c_stub_init(&S[0], K[5], 6, 1);
	r = top_4();
	if (r == CLJ_THROWN) goto F2;
	clj_release(r);
N2: ;
	// form 3 at 14:1
	if (0) {
F3: ;
	if (!clj_load_form_failed(FILE_STR, 14, 1, K[11])) goto fail;
	goto N3;
	}
	clj_c_stub_init(&S[1], K[12], 14, 1);
	clj_c_stub_init(&S[2], CLJ_NIL, 18, 17);
	r = top_5();
	if (r == CLJ_THROWN) goto F3;
	clj_release(r);
N3: ;
	return CLJ_NIL;
fail:
	return CLJ_THROWN;
}
#else
typedef int cljc_unit_disabled;
#endif
