// Generated by clj-compile from <embedded>/clojure/core/async/impl/buffers.clj; do not edit.
#include "compiled_internal.h"

#define FILE_STR (K[0])
#ifdef CLJ_COMPILED_CORE
static clj_value K[15];
static clj_value V[10];
static clj_value B[1];
static const clj_intrinsic *OP[1];
static const clj_fusion_var *F[1];
static clj_node S[4];
static void unit_pools(void);

static clj_value top_0(void);
static clj_value top_1(void);
static clj_value top_2(void);
static clj_value top_3(void);
clj_value clojure_core_async_impl_buffers_fixed_buffer_a1(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs);
CLJC_INLINE clj_value clojure_core_async_impl_buffers_fixed_buffer_a1_i(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs);
static clj_value clojure_core_async_impl_buffers_fixed_buffer(void *ctx, const clj_value *args, size_t n);
static clj_value top_4(void);
clj_value clojure_core_async_impl_buffers_dropping_buffer_a1(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs);
CLJC_INLINE clj_value clojure_core_async_impl_buffers_dropping_buffer_a1_i(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs);
static clj_value clojure_core_async_impl_buffers_dropping_buffer(void *ctx, const clj_value *args, size_t n);
static clj_value top_5(void);
clj_value clojure_core_async_impl_buffers_sliding_buffer_a1(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs);
CLJC_INLINE clj_value clojure_core_async_impl_buffers_sliding_buffer_a1_i(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs);
static clj_value clojure_core_async_impl_buffers_sliding_buffer(void *ctx, const clj_value *args, size_t n);
static clj_value top_6(void);
clj_value clojure_core_async_impl_buffers_promise_buffer_a0(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs);
CLJC_INLINE clj_value clojure_core_async_impl_buffers_promise_buffer_a0_i(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs);
static clj_value clojure_core_async_impl_buffers_promise_buffer(void *ctx, const clj_value *args, size_t n);

#ifdef CLJ_CLOSED
#endif

static clj_value top_0(void) {
	clj_cframe fr = {NULL, NULL, 0, NULL};
	(void)fr;
	clj_eval_top_enter();
#line 2 "<embedded>/clojure/core/async/impl/buffers.clj"
	clj_value t0;
	bool o1;
	clj_value t1 = clj_c_var_borrow(V[0], &o1);
	if (t1 == CLJ_THROWN) {
	goto L1;
	}
	clj_value t2 = K[1];
	clj_value a0[1] = {t2};
	(void)a0;
	t0 = clj_c_invoke(t1, a0, 1);
	(void)t2;
	if (o1) clj_release(t1);
	if (t0 == CLJ_THROWN) {
	goto L1;
	}
	clj_eval_top_leave();
	return t0;
L1: ;
	clj_eval_top_leave();
	return CLJ_THROWN;
}

static clj_value top_1(void) {
	clj_cframe fr = {NULL, NULL, 0, NULL};
	(void)fr;
	clj_eval_top_enter();
#line 2 "<embedded>/clojure/core/async/impl/buffers.clj"
	clj_value t0;
	bool o1;
	clj_value t1 = clj_c_var_borrow(V[1], &o1);
	if (t1 == CLJ_THROWN) {
	goto L1;
	}
	const clj_value *a0 = NULL;
	t0 = clj_c_invoke(t1, a0, 0);
	if (o1) clj_release(t1);
	if (t0 == CLJ_THROWN) {
	goto L1;
	}
	clj_eval_top_leave();
	return t0;
L1: ;
	clj_eval_top_leave();
	return CLJ_THROWN;
}

static clj_value top_2(void) {
	clj_cframe fr = {NULL, NULL, 0, NULL};
	(void)fr;
	clj_eval_top_enter();
#line 2 "<embedded>/clojure/core/async/impl/buffers.clj"
	clj_value t0 = clj_retain(K[2]);
	clj_eval_top_leave();
	return t0;
}

CLJC_INLINE clj_value clojure_core_async_impl_buffers_fixed_buffer_a1_i(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs) {
	(void)self; (void)captured; (void)args; (void)nargs;
	clj_cframe fr = {NULL, captured, 0, NULL};
	(void)fr;
	clj_value l0 = args[0];
	(void)l0;
	clj_ccall cc;
	CLJC_ENTER(&S[0], &cc);
#line 6 "<embedded>/clojure/core/async/impl/buffers.clj"
	clj_value t0;
	bool o1;
	clj_value t1 = clj_c_var_borrow(V[3], &o1);
	CLJC_SITE(&S[0]);
	if (t1 == CLJ_THROWN) {
	goto L1;
	}
	clj_value t2 = l0;
	clj_value a0[1] = {t2};
	(void)a0;
	t0 = clj_c_invoke(t1, a0, 1);
	(void)t2;
	if (o1) clj_release(t1);
	CLJC_SITE(&S[0]);
	if (t0 == CLJ_THROWN) {
	goto L1;
	}
	CLJC_LEAVE(&S[0], &cc);
	return t0;
L1: ;
	CLJC_LEAVE(&S[0], &cc);
	return CLJ_THROWN;
}

CLJC_FRAME clj_value clojure_core_async_impl_buffers_fixed_buffer_a1(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs) { return clojure_core_async_impl_buffers_fixed_buffer_a1_i(self, captured, args, nargs); }

static clj_value clojure_core_async_impl_buffers_fixed_buffer(void *ctx, const clj_value *args, size_t n) {
	const clj_fn *f = ctx;
	switch (n) {
	case 1: return clojure_core_async_impl_buffers_fixed_buffer_a1(clj_from_ptr((void *)f), f->env, args, n);
	default: break;
	}
	return clj_c_arity_error(clj_from_ptr((void *)f), n);
}

static clj_value top_3(void) {
	clj_cframe fr = {NULL, NULL, 0, NULL};
	(void)fr;
	clj_eval_top_enter();
#line 6 "<embedded>/clojure/core/async/impl/buffers.clj"
	clj_value t0 = clj_c_closure(K[4], clojure_core_async_impl_buffers_fixed_buffer, NULL, 0, 0x2, 1, 1);
	clj_var_bind_root(V[2], t0);
	clj_release(t0);
	clj_value t1 = clj_retain(K[5]);
	clj_value t2 = clj_c_def(V[2], t1, false, false);
	clj_release(t1);
	if (t2 == CLJ_THROWN) {
	goto L1;
	}
	clj_eval_top_leave();
	return t2;
L1: ;
	clj_eval_top_leave();
	return CLJ_THROWN;
}

CLJC_INLINE clj_value clojure_core_async_impl_buffers_dropping_buffer_a1_i(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs) {
	(void)self; (void)captured; (void)args; (void)nargs;
	clj_cframe fr = {NULL, captured, 0, NULL};
	(void)fr;
	clj_value l0 = args[0];
	(void)l0;
	clj_ccall cc;
	CLJC_ENTER(&S[1], &cc);
#line 7 "<embedded>/clojure/core/async/impl/buffers.clj"
	clj_value t0;
	bool o1;
	clj_value t1 = clj_c_var_borrow(V[5], &o1);
	CLJC_SITE(&S[1]);
	if (t1 == CLJ_THROWN) {
	goto L1;
	}
	clj_value t2 = l0;
	clj_value a0[1] = {t2};
	(void)a0;
	t0 = clj_c_invoke(t1, a0, 1);
	(void)t2;
	if (o1) clj_release(t1);
	CLJC_SITE(&S[1]);
	if (t0 == CLJ_THROWN) {
	goto L1;
	}
	CLJC_LEAVE(&S[1], &cc);
	return t0;
L1: ;
	CLJC_LEAVE(&S[1], &cc);
	return CLJ_THROWN;
}

CLJC_FRAME clj_value clojure_core_async_impl_buffers_dropping_buffer_a1(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs) { return clojure_core_async_impl_buffers_dropping_buffer_a1_i(self, captured, args, nargs); }

static clj_value clojure_core_async_impl_buffers_dropping_buffer(void *ctx, const clj_value *args, size_t n) {
	const clj_fn *f = ctx;
	switch (n) {
	case 1: return clojure_core_async_impl_buffers_dropping_buffer_a1(clj_from_ptr((void *)f), f->env, args, n);
	default: break;
	}
	return clj_c_arity_error(clj_from_ptr((void *)f), n);
}

static clj_value top_4(void) {
	clj_cframe fr = {NULL, NULL, 0, NULL};
	(void)fr;
	clj_eval_top_enter();
#line 7 "<embedded>/clojure/core/async/impl/buffers.clj"
	clj_value t0 = clj_c_closure(K[7], clojure_core_async_impl_buffers_dropping_buffer, NULL, 0, 0x2, 1, 1);
	clj_var_bind_root(V[4], t0);
	clj_release(t0);
	clj_value t1 = clj_retain(K[8]);
	clj_value t2 = clj_c_def(V[4], t1, false, false);
	clj_release(t1);
	if (t2 == CLJ_THROWN) {
	goto L1;
	}
	clj_eval_top_leave();
	return t2;
L1: ;
	clj_eval_top_leave();
	return CLJ_THROWN;
}

CLJC_INLINE clj_value clojure_core_async_impl_buffers_sliding_buffer_a1_i(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs) {
	(void)self; (void)captured; (void)args; (void)nargs;
	clj_cframe fr = {NULL, captured, 0, NULL};
	(void)fr;
	clj_value l0 = args[0];
	(void)l0;
	clj_ccall cc;
	CLJC_ENTER(&S[2], &cc);
#line 8 "<embedded>/clojure/core/async/impl/buffers.clj"
	clj_value t0;
	bool o1;
	clj_value t1 = clj_c_var_borrow(V[7], &o1);
	CLJC_SITE(&S[2]);
	if (t1 == CLJ_THROWN) {
	goto L1;
	}
	clj_value t2 = l0;
	clj_value a0[1] = {t2};
	(void)a0;
	t0 = clj_c_invoke(t1, a0, 1);
	(void)t2;
	if (o1) clj_release(t1);
	CLJC_SITE(&S[2]);
	if (t0 == CLJ_THROWN) {
	goto L1;
	}
	CLJC_LEAVE(&S[2], &cc);
	return t0;
L1: ;
	CLJC_LEAVE(&S[2], &cc);
	return CLJ_THROWN;
}

CLJC_FRAME clj_value clojure_core_async_impl_buffers_sliding_buffer_a1(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs) { return clojure_core_async_impl_buffers_sliding_buffer_a1_i(self, captured, args, nargs); }

static clj_value clojure_core_async_impl_buffers_sliding_buffer(void *ctx, const clj_value *args, size_t n) {
	const clj_fn *f = ctx;
	switch (n) {
	case 1: return clojure_core_async_impl_buffers_sliding_buffer_a1(clj_from_ptr((void *)f), f->env, args, n);
	default: break;
	}
	return clj_c_arity_error(clj_from_ptr((void *)f), n);
}

static clj_value top_5(void) {
	clj_cframe fr = {NULL, NULL, 0, NULL};
	(void)fr;
	clj_eval_top_enter();
#line 8 "<embedded>/clojure/core/async/impl/buffers.clj"
	clj_value t0 = clj_c_closure(K[10], clojure_core_async_impl_buffers_sliding_buffer, NULL, 0, 0x2, 1, 1);
	clj_var_bind_root(V[6], t0);
	clj_release(t0);
	clj_value t1 = clj_retain(K[11]);
	clj_value t2 = clj_c_def(V[6], t1, false, false);
	clj_release(t1);
	if (t2 == CLJ_THROWN) {
	goto L1;
	}
	clj_eval_top_leave();
	return t2;
L1: ;
	clj_eval_top_leave();
	return CLJ_THROWN;
}

CLJC_INLINE clj_value clojure_core_async_impl_buffers_promise_buffer_a0_i(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs) {
	(void)self; (void)captured; (void)args; (void)nargs;
	clj_cframe fr = {NULL, captured, 0, NULL};
	(void)fr;
	clj_ccall cc;
	CLJC_ENTER(&S[3], &cc);
#line 9 "<embedded>/clojure/core/async/impl/buffers.clj"
	clj_value t0;
	bool o1;
	clj_value t1 = clj_c_var_borrow(V[9], &o1);
	CLJC_SITE(&S[3]);
	if (t1 == CLJ_THROWN) {
	goto L1;
	}
	const clj_value *a0 = NULL;
	t0 = clj_c_invoke(t1, a0, 0);
	if (o1) clj_release(t1);
	CLJC_SITE(&S[3]);
	if (t0 == CLJ_THROWN) {
	goto L1;
	}
	CLJC_LEAVE(&S[3], &cc);
	return t0;
L1: ;
	CLJC_LEAVE(&S[3], &cc);
	return CLJ_THROWN;
}

CLJC_FRAME clj_value clojure_core_async_impl_buffers_promise_buffer_a0(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs) { return clojure_core_async_impl_buffers_promise_buffer_a0_i(self, captured, args, nargs); }

static clj_value clojure_core_async_impl_buffers_promise_buffer(void *ctx, const clj_value *args, size_t n) {
	const clj_fn *f = ctx;
	switch (n) {
	case 0: return clojure_core_async_impl_buffers_promise_buffer_a0(clj_from_ptr((void *)f), f->env, args, n);
	default: break;
	}
	return clj_c_arity_error(clj_from_ptr((void *)f), n);
}

static clj_value top_6(void) {
	clj_cframe fr = {NULL, NULL, 0, NULL};
	(void)fr;
	clj_eval_top_enter();
#line 9 "<embedded>/clojure/core/async/impl/buffers.clj"
	clj_value t0 = clj_c_closure(K[13], clojure_core_async_impl_buffers_promise_buffer, NULL, 0, 0x1, 0, 0);
	clj_var_bind_root(V[8], t0);
	clj_release(t0);
	clj_value t1 = clj_retain(K[14]);
	clj_value t2 = clj_c_def(V[8], t1, false, false);
	clj_release(t1);
	if (t2 == CLJ_THROWN) {
	goto L1;
	}
	clj_eval_top_leave();
	return t2;
L1: ;
	clj_eval_top_leave();
	return CLJ_THROWN;
}

static const clj_frame_entry FR[4] = {
	{(clj_code)clojure_core_async_impl_buffers_fixed_buffer_a1, &S[0]},
	{(clj_code)clojure_core_async_impl_buffers_dropping_buffer_a1, &S[1]},
	{(clj_code)clojure_core_async_impl_buffers_sliding_buffer_a1, &S[2]},
	{(clj_code)clojure_core_async_impl_buffers_promise_buffer_a0, &S[3]},
};

static bool pools_filled;

static void unit_pools(void) {
	(void)K; (void)V; (void)B; (void)OP; (void)F; (void)S;
	pools_filled = true;
	clj_c_register_frames(FR, 4);
	V[0] = clj_c_var("clojure.core", "in-ns");
	V[1] = clj_c_var("clojure.core", "refer-clojure");
	V[2] = clj_c_var("clojure.core.async.impl.buffers", "fixed-buffer");
	V[3] = clj_c_var("clojure.core", "buffer*");
	V[4] = clj_c_var("clojure.core.async.impl.buffers", "dropping-buffer");
	V[5] = clj_c_var("clojure.core", "dropping-buffer*");
	V[6] = clj_c_var("clojure.core.async.impl.buffers", "sliding-buffer");
	V[7] = clj_c_var("clojure.core", "sliding-buffer*");
	V[8] = clj_c_var("clojure.core.async.impl.buffers", "promise-buffer");
	V[9] = clj_c_var("clojure.core", "promise-buffer*");
	K[0] = clj_c_const("\"<embedded>/clojure/core/async/impl/buffers.clj\"", 48);
	K[1] = clj_c_const("clojure.core.async.impl.buffers", 31);
	K[2] = clj_c_const("nil", 3);
	K[3] = clj_c_const("fixed-buffer", 12);
	K[4] = clj_c_const("clojure.core.async.impl.buffers/fixed-buffer", 44);
	K[5] = clj_c_const("{:arglists ([n]), :column 1, :file \"<embedded>/clojure/core/async/impl/buffers.clj\", :line 6, :name fixed-buffer, :ns clojure.core.async.impl.buffers}", 150);
	K[6] = clj_c_const("dropping-buffer", 15);
	K[7] = clj_c_const("clojure.core.async.impl.buffers/dropping-buffer", 47);
	K[8] = clj_c_const("{:arglists ([n]), :column 1, :file \"<embedded>/clojure/core/async/impl/buffers.clj\", :line 7, :name dropping-buffer, :ns clojure.core.async.impl.buffers}", 153);
	K[9] = clj_c_const("sliding-buffer", 14);
	K[10] = clj_c_const("clojure.core.async.impl.buffers/sliding-buffer", 46);
	K[11] = clj_c_const("{:arglists ([n]), :column 1, :file \"<embedded>/clojure/core/async/impl/buffers.clj\", :line 8, :name sliding-buffer, :ns clojure.core.async.impl.buffers}", 152);
	K[12] = clj_c_const("promise-buffer", 14);
	K[13] = clj_c_const("clojure.core.async.impl.buffers/promise-buffer", 46);
	K[14] = clj_c_const("{:arglists ([]), :column 1, :file \"<embedded>/clojure/core/async/impl/buffers.clj\", :line 9, :name promise-buffer, :ns clojure.core.async.impl.buffers}", 151);
}

clj_value clj_compiled_lib_init_clojure_core_async_impl_buffers(void) {
	clj_value r;
	(void)r;
	if (!pools_filled) unit_pools();
#ifdef CLJ_CLOSED
	clj_compiled_register_symbol("clojure_core_async_impl_buffers_fixed_buffer_a1", clojure_core_async_impl_buffers_fixed_buffer_a1);
	clj_compiled_register_symbol("clojure_core_async_impl_buffers_dropping_buffer_a1", clojure_core_async_impl_buffers_dropping_buffer_a1);
	clj_compiled_register_symbol("clojure_core_async_impl_buffers_sliding_buffer_a1", clojure_core_async_impl_buffers_sliding_buffer_a1);
	clj_compiled_register_symbol("clojure_core_async_impl_buffers_promise_buffer_a0", clojure_core_async_impl_buffers_promise_buffer_a0);
#endif
	// form 1 at 2:1
	if (0) {
F1: ;
	if (!clj_load_form_failed(FILE_STR, 2, 1, CLJ_NIL)) goto fail;
	goto N1;
	}
	r = top_0();
	if (r == CLJ_THROWN) goto F1;
	clj_release(r);
	r = top_1();
	if (r == CLJ_THROWN) goto F1;
	clj_release(r);
	r = top_2();
	if (r == CLJ_THROWN) goto F1;
	clj_release(r);
N1: ;
	// form 2 at 6:1
	if (0) {
F2: ;
	if (!clj_load_form_failed(FILE_STR, 6, 1, K[3])) goto fail;
	goto N2;
	}
	clj_c_stub_init(&S[0], K[4], 6, 1);
	r = top_3();
	if (r == CLJ_THROWN) goto F2;
	clj_release(r);
N2: ;
	// form 3 at 7:1
	if (0) {
F3: ;
	if (!clj_load_form_failed(FILE_STR, 7, 1, K[6])) goto fail;
	goto N3;
	}
	clj_c_stub_init(&S[1], K[7], 7, 1);
	r = top_4();
	if (r == CLJ_THROWN) goto F3;
	clj_release(r);
N3: ;
	// form 4 at 8:1
	if (0) {
F4: ;
	if (!clj_load_form_failed(FILE_STR, 8, 1, K[9])) goto fail;
	goto N4;
	}
	clj_c_stub_init(&S[2], K[10], 8, 1);
	r = top_5();
	if (r == CLJ_THROWN) goto F4;
	clj_release(r);
N4: ;
	// form 5 at 9:1
	if (0) {
F5: ;
	if (!clj_load_form_failed(FILE_STR, 9, 1, K[12])) goto fail;
	goto N5;
	}
	clj_c_stub_init(&S[3], K[13], 9, 1);
	r = top_6();
	if (r == CLJ_THROWN) goto F5;
	clj_release(r);
N5: ;
	return CLJ_NIL;
fail:
	return CLJ_THROWN;
}
#else
typedef int cljc_unit_disabled;
#endif
