// Generated by clj-compile from <embedded>/clojure/walk.clj; do not edit.
#include "compiled_internal.h"

#define FILE_STR (K[0])
#ifdef CLJ_COMPILED_CORE
static clj_value K[31];
static clj_value V[30];
static clj_value B[8];
static const clj_intrinsic *OP[8];
static const clj_fusion_var *F[3];
static clj_node S[15];
static void unit_pools(void);

static clj_value top_0(void);
static clj_value top_1(void);
static clj_value top_2(void);
static clj_value top_3(void);
clj_value clojure_walk_walk_a3(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs);
static clj_value clojure_walk_walk(void *ctx, const clj_value *args, size_t n);
static clj_value top_4(void);
clj_value clojure_walk_postwalk_a2(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs);
static clj_value clojure_walk_postwalk(void *ctx, const clj_value *args, size_t n);
static clj_value top_5(void);
clj_value clojure_walk_prewalk_a2(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs);
static clj_value clojure_walk_prewalk(void *ctx, const clj_value *args, size_t n);
static clj_value top_6(void);
clj_value clojure_walk_keywordize_keys_a1(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs);
static clj_value clojure_walk_keywordize_keys__0_a1(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs);
static clj_value clojure_walk_keywordize_keys__0(void *ctx, const clj_value *args, size_t n);
static clj_value clojure_walk_keywordize_keys__1_a1(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs);
static clj_value clojure_walk_keywordize_keys__1(void *ctx, const clj_value *args, size_t n);
static clj_value clojure_walk_keywordize_keys(void *ctx, const clj_value *args, size_t n);
static clj_value top_7(void);
clj_value clojure_walk_stringify_keys_a1(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs);
static clj_value clojure_walk_stringify_keys__0_a1(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs);
static clj_value clojure_walk_stringify_keys__0(void *ctx, const clj_value *args, size_t n);
static clj_value clojure_walk_stringify_keys__1_a1(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs);
static clj_value clojure_walk_stringify_keys__1(void *ctx, const clj_value *args, size_t n);
static clj_value clojure_walk_stringify_keys(void *ctx, const clj_value *args, size_t n);
static clj_value top_8(void);
clj_value clojure_walk_prewalk_replace_a2(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs);
static clj_value clojure_walk_prewalk_replace__0_a1(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs);
static clj_value clojure_walk_prewalk_replace__0(void *ctx, const clj_value *args, size_t n);
static clj_value clojure_walk_prewalk_replace(void *ctx, const clj_value *args, size_t n);
static clj_value top_9(void);
clj_value clojure_walk_postwalk_replace_a2(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs);
static clj_value clojure_walk_postwalk_replace__0_a1(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs);
static clj_value clojure_walk_postwalk_replace__0(void *ctx, const clj_value *args, size_t n);
static clj_value clojure_walk_postwalk_replace(void *ctx, const clj_value *args, size_t n);
static clj_value top_10(void);
clj_value clojure_walk_macroexpand_all_a1(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs);
static clj_value clojure_walk_macroexpand_all__0_a1(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs);
static clj_value clojure_walk_macroexpand_all__0(void *ctx, const clj_value *args, size_t n);
static clj_value clojure_walk_macroexpand_all(void *ctx, const clj_value *args, size_t n);

#ifdef CLJ_CLOSED
#define CLJC_DIRECT_clojure_core_map_a2 1
static clj_compiled_fn CLJC_FN_clojure_core_map_a2;
#define CLJC_DIRECT_clojure_core_doall_a1 1
static clj_compiled_fn CLJC_FN_clojure_core_doall_a1;
#define CLJC_DIRECT_clojure_core_map_a1 1
static clj_compiled_fn CLJC_FN_clojure_core_map_a1;
#define CLJC_DIRECT_clojure_core_partial_a2 1
static clj_compiled_fn CLJC_FN_clojure_core_partial_a2;
#define CLJC_DIRECT_clojure_walk_walk_a3 1
static clj_compiled_fn CLJC_FN_clojure_walk_walk_a3 = clojure_walk_walk_a3;
#define CLJC_DIRECT_clojure_walk_postwalk_a2 1
static clj_compiled_fn CLJC_FN_clojure_walk_postwalk_a2 = clojure_walk_postwalk_a2;
#define CLJC_DIRECT_clojure_walk_prewalk_a2 1
static clj_compiled_fn CLJC_FN_clojure_walk_prewalk_a2 = clojure_walk_prewalk_a2;
#endif

static clj_value top_0(void) {
	clj_cframe fr = {NULL, NULL, 0, NULL};
	(void)fr;
	clj_eval_top_enter();
#line 3 "<embedded>/clojure/walk.clj"
	bool o0;
	clj_value t0 = clj_c_var_borrow(V[0], &o0);
	if (t0 == CLJ_THROWN) {
	goto L1;
	}
	clj_value t1 = K[1];
	clj_value a0[1] = {t1};
	(void)a0;
	clj_value t2 = clj_c_invoke(t0, a0, 1);
	(void)t1;
	if (o0) clj_release(t0);
	if (t2 == CLJ_THROWN) {
	goto L1;
	}
	clj_eval_top_leave();
	return t2;
L1: ;
	clj_eval_top_leave();
	return CLJ_THROWN;
}

static clj_value top_1(void) {
	clj_cframe fr = {NULL, NULL, 0, NULL};
	(void)fr;
	clj_eval_top_enter();
#line 3 "<embedded>/clojure/walk.clj"
	bool o0;
	clj_value t0 = clj_c_var_borrow(V[1], &o0);
	if (t0 == CLJ_THROWN) {
	goto L1;
	}
	const clj_value *a0 = NULL;
	clj_value t1 = clj_c_invoke(t0, a0, 0);
	if (o0) clj_release(t0);
	if (t1 == CLJ_THROWN) {
	goto L1;
	}
	clj_eval_top_leave();
	return t1;
L1: ;
	clj_eval_top_leave();
	return CLJ_THROWN;
}

static clj_value top_2(void) {
	clj_cframe fr = {NULL, NULL, 0, NULL};
	(void)fr;
	clj_eval_top_enter();
#line 3 "<embedded>/clojure/walk.clj"
	clj_value t0 = clj_retain(K[2]);
	clj_eval_top_leave();
	return t0;
}

clj_value clojure_walk_walk_a3(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs) {
	(void)self; (void)captured; (void)args; (void)nargs;
	clj_cframe fr = {NULL, captured, 0, NULL};
	(void)fr;
	clj_value l0 = args[0];
	(void)l0;
	clj_value l1 = args[1];
	(void)l1;
	clj_value l2 = args[2];
	(void)l2;
	clj_ccall cc;
	if (!clj_c_enter(&S[0], &cc)) goto L1;
#line 8 "<embedded>/clojure/walk.clj"
#line 9 "<embedded>/clojure/walk.clj"
	clj_value t0 = l2;
	clj_value a0[1] = {t0};
	(void)a0;
	clj_value t1;
	if (CLJC_GUARD(V[3], B[0])) {
	t1 = clj_list_p(t0);
	} else {
	t1 = clj_c_intrinsic_fallback(V[3], a0, 1);
	}
	(void)t0;
	if (t1 == CLJ_THROWN) {
	goto L2;
	}
	bool t2 = clj_truthy(t1);
	clj_release(t1);
	clj_value t3;
	if (t2) {
	clj_value t4 = l1;
	bool o5;
	clj_value t5 = clj_c_var_borrow(V[4], &o5);
	if (t5 == CLJ_THROWN) {
	goto L2;
	}
	bool o6;
	clj_value t6 = clj_c_var_borrow(V[5], &o6);
	if (t6 == CLJ_THROWN) {
	if (o5) clj_release(t5);
	goto L2;
	}
	bool o7;
	clj_value t7 = clj_c_var_borrow(V[6], &o7);
	if (t7 == CLJ_THROWN) {
	if (o6) clj_release(t6);
	if (o5) clj_release(t5);
	goto L2;
	}
	clj_value t8 = l0;
	clj_value t9 = l2;
	clj_value a3[2] = {t8, t9};
	(void)a3;
	clj_value t10;
#ifdef CLJC_DIRECT_clojure_core_map_a2
	if (!CLJC_FN_clojure_core_map_a2) CLJC_FN_clojure_core_map_a2 = clj_compiled_symbol("clojure_core_map_a2");
	t10 = CLJC_FN_clojure_core_map_a2 ? CLJC_FN_clojure_core_map_a2(clj_var_root_relaxed(V[6]), NULL, a3, 2) : clj_c_invoke(t7, a3, 2);
#else
	t10 = clj_c_invoke(t7, a3, 2);
#endif
	(void)t9;
	(void)t8;
	if (o7) clj_release(t7);
	if (t10 == CLJ_THROWN) {
	if (o6) clj_release(t6);
	if (o5) clj_release(t5);
	goto L2;
	}
	clj_value a2[2] = {t6, t10};
	(void)a2;
	clj_value t11 = clj_c_invoke(t5, a2, 2);
	clj_release(t10);
	if (o6) clj_release(t6);
	if (o5) clj_release(t5);
	if (t11 == CLJ_THROWN) {
	goto L2;
	}
	clj_value a1[1] = {t11};
	(void)a1;
	clj_value t12 = clj_c_invoke(t4, a1, 1);
	clj_release(t11);
	(void)t4;
	if (t12 == CLJ_THROWN) {
	goto L2;
	}
	t3 = t12;
	} else {
#line 8 "<embedded>/clojure/walk.clj"
#line 10 "<embedded>/clojure/walk.clj"
	clj_value t13 = l2;
	clj_value a4[1] = {t13};
	(void)a4;
	clj_value t14;
	if (CLJC_GUARD(V[7], B[1])) {
	t14 = clj_seq_p(t13);
	} else {
	t14 = clj_c_intrinsic_fallback(V[7], a4, 1);
	}
	(void)t13;
	if (t14 == CLJ_THROWN) {
	goto L2;
	}
	bool t15 = clj_truthy(t14);
	clj_release(t14);
	clj_value t16;
	if (t15) {
	clj_value t17 = l1;
	bool o18;
	clj_value t18 = clj_c_var_borrow(V[8], &o18);
	if (t18 == CLJ_THROWN) {
	goto L2;
	}
	bool o19;
	clj_value t19 = clj_c_var_borrow(V[6], &o19);
	if (t19 == CLJ_THROWN) {
	if (o18) clj_release(t18);
	goto L2;
	}
	clj_value t20 = l0;
	clj_value t21 = l2;
	clj_value a7[2] = {t20, t21};
	(void)a7;
	clj_value t22;
#ifdef CLJC_DIRECT_clojure_core_map_a2
	if (!CLJC_FN_clojure_core_map_a2) CLJC_FN_clojure_core_map_a2 = clj_compiled_symbol("clojure_core_map_a2");
	t22 = CLJC_FN_clojure_core_map_a2 ? CLJC_FN_clojure_core_map_a2(clj_var_root_relaxed(V[6]), NULL, a7, 2) : clj_c_invoke(t19, a7, 2);
#else
	t22 = clj_c_invoke(t19, a7, 2);
#endif
	(void)t21;
	(void)t20;
	if (o19) clj_release(t19);
	if (t22 == CLJ_THROWN) {
	if (o18) clj_release(t18);
	goto L2;
	}
	clj_value a6[1] = {t22};
	(void)a6;
	clj_value t23;
#ifdef CLJC_DIRECT_clojure_core_doall_a1
	if (!CLJC_FN_clojure_core_doall_a1) CLJC_FN_clojure_core_doall_a1 = clj_compiled_symbol("clojure_core_doall_a1");
	t23 = CLJC_FN_clojure_core_doall_a1 ? CLJC_FN_clojure_core_doall_a1(clj_var_root_relaxed(V[8]), NULL, a6, 1) : clj_c_invoke(t18, a6, 1);
#else
	t23 = clj_c_invoke(t18, a6, 1);
#endif
	clj_release(t22);
	if (o18) clj_release(t18);
	if (t23 == CLJ_THROWN) {
	goto L2;
	}
	clj_value a5[1] = {t23};
	(void)a5;
	clj_value t24 = clj_c_invoke(t17, a5, 1);
	clj_release(t23);
	(void)t17;
	if (t24 == CLJ_THROWN) {
	goto L2;
	}
	t16 = t24;
	} else {
#line 8 "<embedded>/clojure/walk.clj"
#line 11 "<embedded>/clojure/walk.clj"
	clj_value t25 = l2;
	clj_value a8[1] = {t25};
	(void)a8;
	clj_value t26;
	if (CLJC_GUARD(V[9], B[2])) {
	t26 = clj_coll_p(t25);
	} else {
	t26 = clj_c_intrinsic_fallback(V[9], a8, 1);
	}
	(void)t25;
	if (t26 == CLJ_THROWN) {
	goto L2;
	}
	bool t27 = clj_truthy(t26);
	clj_release(t26);
	clj_value t28;
	if (t27) {
	clj_value t29 = l1;
	bool o30;
	clj_value t30 = clj_c_var_borrow(V[10], &o30);
	if (t30 == CLJ_THROWN) {
	goto L2;
	}
	clj_value t31 = l2;
	clj_value a11[1] = {t31};
	(void)a11;
	clj_value t32 = clj_c_invoke(t30, a11, 1);
	(void)t31;
	if (o30) clj_release(t30);
	if (t32 == CLJ_THROWN) {
	goto L2;
	}
	clj_value t33 = l0;
	clj_value t34 = l2;
	clj_value a10[3] = {t32, t33, t34};
	(void)a10;
	clj_cframe fr10 = {(clj_value *)a10, NULL, 0, NULL};
	(void)fr10;
	clj_value t35;
	{
	const clj_fusion_var *g10[3] = {F[0], F[1], F[2]};
	(void)g10;
	if (CLJC_FUSED(g10, 3)) {
	bool o36;
	clj_value t36 = clj_c_var_borrow(V[11], &o36);
	if (t36 == CLJ_THROWN) {
	clj_release(t32);
	goto L2;
	}
	clj_value t37 = fr10.slots[0];
	clj_value t38 = fr10.slots[2];
	bool o39;
	clj_value t39 = clj_c_var_borrow(V[6], &o39);
	if (t39 == CLJ_THROWN) {
	if (o36) clj_release(t36);
	clj_release(t32);
	goto L2;
	}
	clj_value t40 = fr10.slots[1];
	clj_value a14[1] = {t40};
	(void)a14;
	clj_value t41;
#ifdef CLJC_DIRECT_clojure_core_map_a1
	if (!CLJC_FN_clojure_core_map_a1) CLJC_FN_clojure_core_map_a1 = clj_compiled_symbol("clojure_core_map_a1");
	t41 = CLJC_FN_clojure_core_map_a1 ? CLJC_FN_clojure_core_map_a1(clj_var_root_relaxed(V[6]), NULL, a14, 1) : clj_c_invoke(t39, a14, 1);
#else
	t41 = clj_c_invoke(t39, a14, 1);
#endif
	(void)t40;
	if (o39) clj_release(t39);
	if (t41 == CLJ_THROWN) {
	if (o36) clj_release(t36);
	clj_release(t32);
	goto L2;
	}
	clj_value a13[1] = {t41};
	(void)a13;
	clj_value t42 = clj_vector_from_array(a13, 1);
	clj_release(t41);
	if (t42 == CLJ_THROWN) {
	if (o36) clj_release(t36);
	clj_release(t32);
	goto L2;
	}
	clj_value a12[3] = {t37, t38, t42};
	(void)a12;
	clj_value t43 = clj_c_invoke(t36, a12, 3);
	clj_release(t42);
	(void)t38;
	(void)t37;
	if (o36) clj_release(t36);
	if (t43 == CLJ_THROWN) {
	clj_release(t32);
	goto L2;
	}
	t35 = t43;
	} else {
	bool o44;
	clj_value t44 = clj_c_var_borrow(V[12], &o44);
	if (t44 == CLJ_THROWN) {
	clj_release(t32);
	goto L2;
	}
	clj_value t45 = fr10.slots[0];
	bool o46;
	clj_value t46 = clj_c_var_borrow(V[6], &o46);
	if (t46 == CLJ_THROWN) {
	if (o44) clj_release(t44);
	clj_release(t32);
	goto L2;
	}
	clj_value t47 = fr10.slots[1];
	clj_value t48 = fr10.slots[2];
	clj_value a16[2] = {t47, t48};
	(void)a16;
	clj_value t49;
#ifdef CLJC_DIRECT_clojure_core_map_a2
	if (!CLJC_FN_clojure_core_map_a2) CLJC_FN_clojure_core_map_a2 = clj_compiled_symbol("clojure_core_map_a2");
	t49 = CLJC_FN_clojure_core_map_a2 ? CLJC_FN_clojure_core_map_a2(clj_var_root_relaxed(V[6]), NULL, a16, 2) : clj_c_invoke(t46, a16, 2);
#else
	t49 = clj_c_invoke(t46, a16, 2);
#endif
	(void)t48;
	(void)t47;
	if (o46) clj_release(t46);
	if (t49 == CLJ_THROWN) {
	if (o44) clj_release(t44);
	clj_release(t32);
	goto L2;
	}
	clj_value a15[2] = {t45, t49};
	(void)a15;
	clj_value t50 = clj_c_invoke(t44, a15, 2);
	clj_release(t49);
	(void)t45;
	if (o44) clj_release(t44);
	if (t50 == CLJ_THROWN) {
	clj_release(t32);
	goto L2;
	}
	t35 = t50;
	}
	}
	(void)t34;
	(void)t33;
	clj_release(t32);
	clj_value a9[1] = {t35};
	(void)a9;
	clj_value t51 = clj_c_invoke(t29, a9, 1);
	clj_release(t35);
	(void)t29;
	if (t51 == CLJ_THROWN) {
	goto L2;
	}
	t28 = t51;
	} else {
#line 12 "<embedded>/clojure/walk.clj"
	clj_value t52 = l1;
	clj_value t53 = l2;
	clj_value a17[1] = {t53};
	(void)a17;
	clj_value t54 = clj_c_invoke(t52, a17, 1);
	(void)t53;
	(void)t52;
	if (t54 == CLJ_THROWN) {
	goto L2;
	}
	t28 = t54;
	}
	t16 = t28;
	}
	t3 = t16;
	}
	clj_c_leave(&S[0], &cc);
	return t3;
L2: ;
	clj_c_leave(&S[0], &cc);
L1: ;
	return CLJ_THROWN;
}

static clj_value clojure_walk_walk(void *ctx, const clj_value *args, size_t n) {
	const clj_fn *f = ctx;
	switch (n) {
	case 3: return clojure_walk_walk_a3(clj_from_ptr((void *)f), f->env, args, n);
	default: break;
	}
	return clj_c_arity_error(clj_from_ptr((void *)f), n);
}

static clj_value top_3(void) {
	clj_cframe fr = {NULL, NULL, 0, NULL};
	(void)fr;
	clj_eval_top_enter();
#line 5 "<embedded>/clojure/walk.clj"
	clj_value t0 = clj_c_closure(K[4], clojure_walk_walk, NULL, 0, 0x8, 3, 3);
	clj_var_bind_root(V[2], t0);
	clj_release(t0);
	clj_value t1 = clj_retain(K[5]);
	clj_value t2 = clj_c_def(V[2], t1, false, false);
	clj_release(t1);
	if (t2 == CLJ_THROWN) {
	goto L1;
	}
	clj_eval_top_leave();
	return t2;
L1: ;
	clj_eval_top_leave();
	return CLJ_THROWN;
}

clj_value clojure_walk_postwalk_a2(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs) {
	(void)self; (void)captured; (void)args; (void)nargs;
	clj_cframe fr = {NULL, captured, 0, NULL};
	(void)fr;
	clj_value l0 = args[0];
	(void)l0;
	clj_value l1 = args[1];
	(void)l1;
	clj_ccall cc;
	if (!clj_c_enter(&S[1], &cc)) goto L1;
#line 17 "<embedded>/clojure/walk.clj"
	bool o0;
	clj_value t0 = clj_c_var_borrow(V[2], &o0);
	if (t0 == CLJ_THROWN) {
	goto L2;
	}
	bool o1;
	clj_value t1 = clj_c_var_borrow(V[14], &o1);
	if (t1 == CLJ_THROWN) {
	if (o0) clj_release(t0);
	goto L2;
	}
	bool o2;
	clj_value t2 = clj_c_var_borrow(V[13], &o2);
	if (t2 == CLJ_THROWN) {
	if (o1) clj_release(t1);
	if (o0) clj_release(t0);
	goto L2;
	}
	clj_value t3 = l0;
	clj_value a1[2] = {t2, t3};
	(void)a1;
	clj_value t4;
#ifdef CLJC_DIRECT_clojure_core_partial_a2
	if (!CLJC_FN_clojure_core_partial_a2) CLJC_FN_clojure_core_partial_a2 = clj_compiled_symbol("clojure_core_partial_a2");
	t4 = CLJC_FN_clojure_core_partial_a2 ? CLJC_FN_clojure_core_partial_a2(clj_var_root_relaxed(V[14]), NULL, a1, 2) : clj_c_invoke(t1, a1, 2);
#else
	t4 = clj_c_invoke(t1, a1, 2);
#endif
	(void)t3;
	if (o2) clj_release(t2);
	if (o1) clj_release(t1);
	if (t4 == CLJ_THROWN) {
	if (o0) clj_release(t0);
	goto L2;
	}
	clj_value t5 = l0;
	clj_value t6 = l1;
	clj_value a0[3] = {t4, t5, t6};
	(void)a0;
	clj_value t7;
#ifdef CLJC_DIRECT_clojure_walk_walk_a3
	if (!CLJC_FN_clojure_walk_walk_a3) CLJC_FN_clojure_walk_walk_a3 = clj_compiled_symbol("clojure_walk_walk_a3");
	t7 = CLJC_FN_clojure_walk_walk_a3 ? CLJC_FN_clojure_walk_walk_a3(clj_var_root_relaxed(V[2]), NULL, a0, 3) : clj_c_invoke(t0, a0, 3);
#else
	t7 = clj_c_invoke(t0, a0, 3);
#endif
	(void)t6;
	(void)t5;
	clj_release(t4);
	if (o0) clj_release(t0);
	if (t7 == CLJ_THROWN) {
	goto L2;
	}
	clj_c_leave(&S[1], &cc);
	return t7;
L2: ;
	clj_c_leave(&S[1], &cc);
L1: ;
	return CLJ_THROWN;
}

static clj_value clojure_walk_postwalk(void *ctx, const clj_value *args, size_t n) {
	const clj_fn *f = ctx;
	switch (n) {
	case 2: return clojure_walk_postwalk_a2(clj_from_ptr((void *)f), f->env, args, n);
	default: break;
	}
	return clj_c_arity_error(clj_from_ptr((void *)f), n);
}

static clj_value top_4(void) {
	clj_cframe fr = {NULL, NULL, 0, NULL};
	(void)fr;
	clj_eval_top_enter();
#line 14 "<embedded>/clojure/walk.clj"
	clj_value t0 = clj_c_closure(K[7], clojure_walk_postwalk, NULL, 0, 0x4, 2, 2);
	clj_var_bind_root(V[13], t0);
	clj_release(t0);
	clj_value t1 = clj_retain(K[8]);
	clj_value t2 = clj_c_def(V[13], t1, false, false);
	clj_release(t1);
	if (t2 == CLJ_THROWN) {
	goto L1;
	}
	clj_eval_top_leave();
	return t2;
L1: ;
	clj_eval_top_leave();
	return CLJ_THROWN;
}

clj_value clojure_walk_prewalk_a2(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs) {
	(void)self; (void)captured; (void)args; (void)nargs;
	clj_cframe fr = {NULL, captured, 0, NULL};
	(void)fr;
	clj_value l0 = args[0];
	(void)l0;
	clj_value l1 = args[1];
	(void)l1;
	clj_ccall cc;
	if (!clj_c_enter(&S[2], &cc)) goto L1;
#line 22 "<embedded>/clojure/walk.clj"
	bool o0;
	clj_value t0 = clj_c_var_borrow(V[2], &o0);
	if (t0 == CLJ_THROWN) {
	goto L2;
	}
	bool o1;
	clj_value t1 = clj_c_var_borrow(V[14], &o1);
	if (t1 == CLJ_THROWN) {
	if (o0) clj_release(t0);
	goto L2;
	}
	bool o2;
	clj_value t2 = clj_c_var_borrow(V[15], &o2);
	if (t2 == CLJ_THROWN) {
	if (o1) clj_release(t1);
	if (o0) clj_release(t0);
	goto L2;
	}
	clj_value t3 = l0;
	clj_value a1[2] = {t2, t3};
	(void)a1;
	clj_value t4;
#ifdef CLJC_DIRECT_clojure_core_partial_a2
	if (!CLJC_FN_clojure_core_partial_a2) CLJC_FN_clojure_core_partial_a2 = clj_compiled_symbol("clojure_core_partial_a2");
	t4 = CLJC_FN_clojure_core_partial_a2 ? CLJC_FN_clojure_core_partial_a2(clj_var_root_relaxed(V[14]), NULL, a1, 2) : clj_c_invoke(t1, a1, 2);
#else
	t4 = clj_c_invoke(t1, a1, 2);
#endif
	(void)t3;
	if (o2) clj_release(t2);
	if (o1) clj_release(t1);
	if (t4 == CLJ_THROWN) {
	if (o0) clj_release(t0);
	goto L2;
	}
	bool o5;
	clj_value t5 = clj_c_var_borrow(V[16], &o5);
	if (t5 == CLJ_THROWN) {
	clj_release(t4);
	if (o0) clj_release(t0);
	goto L2;
	}
	clj_value t6 = l0;
	clj_value t7 = l1;
	clj_value a2[1] = {t7};
	(void)a2;
	clj_value t8 = clj_c_invoke(t6, a2, 1);
	(void)t7;
	(void)t6;
	if (t8 == CLJ_THROWN) {
	if (o5) clj_release(t5);
	clj_release(t4);
	if (o0) clj_release(t0);
	goto L2;
	}
	clj_value a0[3] = {t4, t5, t8};
	(void)a0;
	clj_value t9;
#ifdef CLJC_DIRECT_clojure_walk_walk_a3
	if (!CLJC_FN_clojure_walk_walk_a3) CLJC_FN_clojure_walk_walk_a3 = clj_compiled_symbol("clojure_walk_walk_a3");
	t9 = CLJC_FN_clojure_walk_walk_a3 ? CLJC_FN_clojure_walk_walk_a3(clj_var_root_relaxed(V[2]), NULL, a0, 3) : clj_c_invoke(t0, a0, 3);
#else
	t9 = clj_c_invoke(t0, a0, 3);
#endif
	clj_release(t8);
	if (o5) clj_release(t5);
	clj_release(t4);
	if (o0) clj_release(t0);
	if (t9 == CLJ_THROWN) {
	goto L2;
	}
	clj_c_leave(&S[2], &cc);
	return t9;
L2: ;
	clj_c_leave(&S[2], &cc);
L1: ;
	return CLJ_THROWN;
}

static clj_value clojure_walk_prewalk(void *ctx, const clj_value *args, size_t n) {
	const clj_fn *f = ctx;
	switch (n) {
	case 2: return clojure_walk_prewalk_a2(clj_from_ptr((void *)f), f->env, args, n);
	default: break;
	}
	return clj_c_arity_error(clj_from_ptr((void *)f), n);
}

static clj_value top_5(void) {
	clj_cframe fr = {NULL, NULL, 0, NULL};
	(void)fr;
	clj_eval_top_enter();
#line 19 "<embedded>/clojure/walk.clj"
	clj_value t0 = clj_c_closure(K[10], clojure_walk_prewalk, NULL, 0, 0x4, 2, 2);
	clj_var_bind_root(V[15], t0);
	clj_release(t0);
	clj_value t1 = clj_retain(K[11]);
	clj_value t2 = clj_c_def(V[15], t1, false, false);
	clj_release(t1);
	if (t2 == CLJ_THROWN) {
	goto L1;
	}
	clj_eval_top_leave();
	return t2;
L1: ;
	clj_eval_top_leave();
	return CLJ_THROWN;
}

static clj_value clojure_walk_keywordize_keys__0_a1(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs) {
	(void)self; (void)captured; (void)args; (void)nargs;
	clj_cframe fr = {NULL, captured, 0, NULL};
	(void)fr;
	clj_value l0 = args[0];
	(void)l0;
	clj_value l1 = CLJ_NIL;
	clj_value l2 = CLJ_NIL;
	clj_value l3 = CLJ_NIL;
	clj_ccall cc;
	if (!clj_c_enter(&S[4], &cc)) goto L1;
#line 27 "<embedded>/clojure/walk.clj"
	clj_value t0 = clj_retain(l0);
	clj_c_rebind(&l1, t0);
	clj_value t1 = l1;
	clj_value t2 = K[14];
	clj_value t3 = K[2];
	clj_value a0[3] = {t1, t2, t3};
	(void)a0;
	clj_value t4;
	if (CLJC_GUARD(V[18], B[3])) {
	t4 = clj_nth3(t1, t2, t3);
	} else {
	t4 = clj_c_intrinsic_fallback(V[18], a0, 3);
	}
	(void)t3;
	(void)t2;
	(void)t1;
	if (t4 == CLJ_THROWN) {
	goto L2;
	}
	clj_c_rebind(&l2, t4);
	clj_value t5 = l1;
	clj_value t6 = K[15];
	clj_value t7 = K[2];
	clj_value a1[3] = {t5, t6, t7};
	(void)a1;
	clj_value t8;
	if (CLJC_GUARD(V[18], B[3])) {
	t8 = clj_nth3(t5, t6, t7);
	} else {
	t8 = clj_c_intrinsic_fallback(V[18], a1, 3);
	}
	(void)t7;
	(void)t6;
	(void)t5;
	if (t8 == CLJ_THROWN) {
	goto L2;
	}
	clj_c_rebind(&l3, t8);
	clj_value t9 = l2;
	clj_value a2[1] = {t9};
	(void)a2;
	clj_value t10;
	if (CLJC_GUARD(V[19], B[4])) {
	t10 = clj_string_p(t9);
	} else {
	t10 = clj_c_intrinsic_fallback(V[19], a2, 1);
	}
	(void)t9;
	if (t10 == CLJ_THROWN) {
	goto L2;
	}
	bool t11 = clj_truthy(t10);
	clj_release(t10);
	clj_value t12;
	if (t11) {
	bool o13;
	clj_value t13 = clj_c_var_borrow(V[20], &o13);
	if (t13 == CLJ_THROWN) {
	goto L2;
	}
	clj_value t14 = l2;
	clj_value a4[1] = {t14};
	(void)a4;
	clj_value t15 = clj_c_invoke(t13, a4, 1);
	(void)t14;
	if (o13) clj_release(t13);
	if (t15 == CLJ_THROWN) {
	goto L2;
	}
	clj_value t16 = l3;
	clj_value a3[2] = {t15, t16};
	(void)a3;
	clj_value t17 = clj_vector_from_array(a3, 2);
	(void)t16;
	clj_release(t15);
	if (t17 == CLJ_THROWN) {
	goto L2;
	}
	t12 = t17;
	} else {
	clj_value t18 = l2;
	clj_value t19 = l3;
	clj_value a5[2] = {t18, t19};
	(void)a5;
	clj_value t20 = clj_vector_from_array(a5, 2);
	(void)t19;
	(void)t18;
	if (t20 == CLJ_THROWN) {
	goto L2;
	}
	t12 = t20;
	}
	clj_c_leave(&S[4], &cc);
	clj_release(l1);
	clj_release(l2);
	clj_release(l3);
	return t12;
L2: ;
	clj_c_leave(&S[4], &cc);
L1: ;
	clj_release(l1);
	clj_release(l2);
	clj_release(l3);
	return CLJ_THROWN;
}

static clj_value clojure_walk_keywordize_keys__0(void *ctx, const clj_value *args, size_t n) {
	const clj_fn *f = ctx;
	switch (n) {
	case 1: return clojure_walk_keywordize_keys__0_a1(clj_from_ptr((void *)f), f->env, args, n);
	default: break;
	}
	return clj_c_arity_error(clj_from_ptr((void *)f), n);
}

static clj_value clojure_walk_keywordize_keys__1_a1(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs) {
	(void)self; (void)captured; (void)args; (void)nargs;
	clj_cframe fr = {NULL, captured, 0, NULL};
	(void)fr;
	clj_value l0 = args[0];
	(void)l0;
	clj_ccall cc;
	if (!clj_c_enter(&S[5], &cc)) goto L1;
#line 28 "<embedded>/clojure/walk.clj"
	clj_value t0 = l0;
	clj_value a0[1] = {t0};
	(void)a0;
	clj_value t1;
	if (CLJC_GUARD(V[21], B[5])) {
	t1 = clj_map_p(t0);
	} else {
	t1 = clj_c_intrinsic_fallback(V[21], a0, 1);
	}
	(void)t0;
	if (t1 == CLJ_THROWN) {
	goto L2;
	}
	bool t2 = clj_truthy(t1);
	clj_release(t1);
	clj_value t3;
	if (t2) {
	clj_value t4 = K[16];
	clj_value t5 = fr.captured[0];
	clj_value t6 = l0;
	clj_value a1[3] = {t4, t5, t6};
	(void)a1;
	clj_cframe fr1 = {(clj_value *)a1, NULL, 0, NULL};
	(void)fr1;
	clj_value t7;
	{
	const clj_fusion_var *g1[3] = {F[0], F[1], F[2]};
	(void)g1;
	if (CLJC_FUSED(g1, 3)) {
	bool o8;
	clj_value t8 = clj_c_var_borrow(V[11], &o8);
	if (t8 == CLJ_THROWN) {
	goto L2;
	}
	clj_value t9 = fr1.slots[0];
	clj_value t10 = fr1.slots[2];
	bool o11;
	clj_value t11 = clj_c_var_borrow(V[6], &o11);
	if (t11 == CLJ_THROWN) {
	if (o8) clj_release(t8);
	goto L2;
	}
	clj_value t12 = fr1.slots[1];
	clj_value a4[1] = {t12};
	(void)a4;
	clj_value t13;
#ifdef CLJC_DIRECT_clojure_core_map_a1
	if (!CLJC_FN_clojure_core_map_a1) CLJC_FN_clojure_core_map_a1 = clj_compiled_symbol("clojure_core_map_a1");
	t13 = CLJC_FN_clojure_core_map_a1 ? CLJC_FN_clojure_core_map_a1(clj_var_root_relaxed(V[6]), NULL, a4, 1) : clj_c_invoke(t11, a4, 1);
#else
	t13 = clj_c_invoke(t11, a4, 1);
#endif
	(void)t12;
	if (o11) clj_release(t11);
	if (t13 == CLJ_THROWN) {
	if (o8) clj_release(t8);
	goto L2;
	}
	clj_value a3[1] = {t13};
	(void)a3;
	clj_value t14 = clj_vector_from_array(a3, 1);
	clj_release(t13);
	if (t14 == CLJ_THROWN) {
	if (o8) clj_release(t8);
	goto L2;
	}
	clj_value a2[3] = {t9, t10, t14};
	(void)a2;
	clj_value t15 = clj_c_invoke(t8, a2, 3);
	clj_release(t14);
	(void)t10;
	(void)t9;
	if (o8) clj_release(t8);
	if (t15 == CLJ_THROWN) {
	goto L2;
	}
	t7 = t15;
	} else {
	bool o16;
	clj_value t16 = clj_c_var_borrow(V[12], &o16);
	if (t16 == CLJ_THROWN) {
	goto L2;
	}
	clj_value t17 = fr1.slots[0];
	bool o18;
	clj_value t18 = clj_c_var_borrow(V[6], &o18);
	if (t18 == CLJ_THROWN) {
	if (o16) clj_release(t16);
	goto L2;
	}
	clj_value t19 = fr1.slots[1];
	clj_value t20 = fr1.slots[2];
	clj_value a6[2] = {t19, t20};
	(void)a6;
	clj_value t21;
#ifdef CLJC_DIRECT_clojure_core_map_a2
	if (!CLJC_FN_clojure_core_map_a2) CLJC_FN_clojure_core_map_a2 = clj_compiled_symbol("clojure_core_map_a2");
	t21 = CLJC_FN_clojure_core_map_a2 ? CLJC_FN_clojure_core_map_a2(clj_var_root_relaxed(V[6]), NULL, a6, 2) : clj_c_invoke(t18, a6, 2);
#else
	t21 = clj_c_invoke(t18, a6, 2);
#endif
	(void)t20;
	(void)t19;
	if (o18) clj_release(t18);
	if (t21 == CLJ_THROWN) {
	if (o16) clj_release(t16);
	goto L2;
	}
	clj_value a5[2] = {t17, t21};
	(void)a5;
	clj_value t22 = clj_c_invoke(t16, a5, 2);
	clj_release(t21);
	(void)t17;
	if (o16) clj_release(t16);
	if (t22 == CLJ_THROWN) {
	goto L2;
	}
	t7 = t22;
	}
	}
	(void)t6;
	(void)t5;
	(void)t4;
	t3 = t7;
	} else {
	clj_value t23 = clj_retain(l0);
	t3 = t23;
	}
	clj_c_leave(&S[5], &cc);
	return t3;
L2: ;
	clj_c_leave(&S[5], &cc);
L1: ;
	return CLJ_THROWN;
}

static clj_value clojure_walk_keywordize_keys__1(void *ctx, const clj_value *args, size_t n) {
	const clj_fn *f = ctx;
	switch (n) {
	case 1: return clojure_walk_keywordize_keys__1_a1(clj_from_ptr((void *)f), f->env, args, n);
	default: break;
	}
	return clj_c_arity_error(clj_from_ptr((void *)f), n);
}

clj_value clojure_walk_keywordize_keys_a1(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs) {
	(void)self; (void)captured; (void)args; (void)nargs;
	clj_value s[2];
	clj_cframe fr = {s, captured, 0, NULL};
	(void)fr;
	clj_value l0 = args[0];
	(void)l0;
	for (uint32_t i = 1; i < 2; i++) s[i] = CLJ_NIL;
	clj_ccall cc;
	if (!clj_c_enter(&S[3], &cc)) goto L1;
#line 27 "<embedded>/clojure/walk.clj"
	clj_value t0 = clj_c_closure(CLJ_NIL, clojure_walk_keywordize_keys__0, NULL, 0, 0x2, 1, 1);
	clj_c_set(&fr, 1, t0);
#line 28 "<embedded>/clojure/walk.clj"
	bool o1;
	clj_value t1 = clj_c_var_borrow(V[13], &o1);
	if (t1 == CLJ_THROWN) {
	goto L2;
	}
	clj_value c1[1] = {fr.slots[1]};
	clj_value t2 = clj_c_closure(CLJ_NIL, clojure_walk_keywordize_keys__1, c1, 1, 0x2, 1, 1);
	clj_value t3 = l0;
	clj_value a0[2] = {t2, t3};
	(void)a0;
	clj_value t4;
#ifdef CLJC_DIRECT_clojure_walk_postwalk_a2
	if (!CLJC_FN_clojure_walk_postwalk_a2) CLJC_FN_clojure_walk_postwalk_a2 = clj_compiled_symbol("clojure_walk_postwalk_a2");
	t4 = CLJC_FN_clojure_walk_postwalk_a2 ? CLJC_FN_clojure_walk_postwalk_a2(clj_var_root_relaxed(V[13]), NULL, a0, 2) : clj_c_invoke(t1, a0, 2);
#else
	t4 = clj_c_invoke(t1, a0, 2);
#endif
	(void)t3;
	clj_release(t2);
	if (o1) clj_release(t1);
	if (t4 == CLJ_THROWN) {
	goto L2;
	}
	clj_c_leave(&S[3], &cc);
	clj_c_release_slots(&fr, 2);
	return t4;
L2: ;
	clj_c_leave(&S[3], &cc);
L1: ;
	clj_c_release_slots(&fr, 2);
	return CLJ_THROWN;
}

static clj_value clojure_walk_keywordize_keys(void *ctx, const clj_value *args, size_t n) {
	const clj_fn *f = ctx;
	switch (n) {
	case 1: return clojure_walk_keywordize_keys_a1(clj_from_ptr((void *)f), f->env, args, n);
	default: break;
	}
	return clj_c_arity_error(clj_from_ptr((void *)f), n);
}

static clj_value top_6(void) {
	clj_cframe fr = {NULL, NULL, 0, NULL};
	(void)fr;
	clj_eval_top_enter();
#line 24 "<embedded>/clojure/walk.clj"
	clj_value t0 = clj_c_closure(K[13], clojure_walk_keywordize_keys, NULL, 0, 0x2, 1, 1);
	clj_var_bind_root(V[17], t0);
	clj_release(t0);
	clj_value t1 = clj_retain(K[17]);
	clj_value t2 = clj_c_def(V[17], t1, false, false);
	clj_release(t1);
	if (t2 == CLJ_THROWN) {
	goto L1;
	}
	clj_eval_top_leave();
	return t2;
L1: ;
	clj_eval_top_leave();
	return CLJ_THROWN;
}

static clj_value clojure_walk_stringify_keys__0_a1(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs) {
	(void)self; (void)captured; (void)args; (void)nargs;
	clj_cframe fr = {NULL, captured, 0, NULL};
	(void)fr;
	clj_value l0 = args[0];
	(void)l0;
	clj_value l1 = CLJ_NIL;
	clj_value l2 = CLJ_NIL;
	clj_value l3 = CLJ_NIL;
	clj_ccall cc;
	if (!clj_c_enter(&S[7], &cc)) goto L1;
#line 33 "<embedded>/clojure/walk.clj"
	clj_value t0 = clj_retain(l0);
	clj_c_rebind(&l1, t0);
	clj_value t1 = l1;
	clj_value t2 = K[14];
	clj_value t3 = K[2];
	clj_value a0[3] = {t1, t2, t3};
	(void)a0;
	clj_value t4;
	if (CLJC_GUARD(V[18], B[3])) {
	t4 = clj_nth3(t1, t2, t3);
	} else {
	t4 = clj_c_intrinsic_fallback(V[18], a0, 3);
	}
	(void)t3;
	(void)t2;
	(void)t1;
	if (t4 == CLJ_THROWN) {
	goto L2;
	}
	clj_c_rebind(&l2, t4);
	clj_value t5 = l1;
	clj_value t6 = K[15];
	clj_value t7 = K[2];
	clj_value a1[3] = {t5, t6, t7};
	(void)a1;
	clj_value t8;
	if (CLJC_GUARD(V[18], B[3])) {
	t8 = clj_nth3(t5, t6, t7);
	} else {
	t8 = clj_c_intrinsic_fallback(V[18], a1, 3);
	}
	(void)t7;
	(void)t6;
	(void)t5;
	if (t8 == CLJ_THROWN) {
	goto L2;
	}
	clj_c_rebind(&l3, t8);
	clj_value t9 = l2;
	clj_value a2[1] = {t9};
	(void)a2;
	clj_value t10;
	if (CLJC_GUARD(V[23], B[6])) {
	t10 = clj_keyword_p(t9);
	} else {
	t10 = clj_c_intrinsic_fallback(V[23], a2, 1);
	}
	(void)t9;
	if (t10 == CLJ_THROWN) {
	goto L2;
	}
	bool t11 = clj_truthy(t10);
	clj_release(t10);
	clj_value t12;
	if (t11) {
	bool o13;
	clj_value t13 = clj_c_var_borrow(V[24], &o13);
	if (t13 == CLJ_THROWN) {
	goto L2;
	}
	clj_value t14 = l2;
	clj_value a4[1] = {t14};
	(void)a4;
	clj_value t15 = clj_c_invoke(t13, a4, 1);
	(void)t14;
	if (o13) clj_release(t13);
	if (t15 == CLJ_THROWN) {
	goto L2;
	}
	clj_value t16 = l3;
	clj_value a3[2] = {t15, t16};
	(void)a3;
	clj_value t17 = clj_vector_from_array(a3, 2);
	(void)t16;
	clj_release(t15);
	if (t17 == CLJ_THROWN) {
	goto L2;
	}
	t12 = t17;
	} else {
	clj_value t18 = l2;
	clj_value t19 = l3;
	clj_value a5[2] = {t18, t19};
	(void)a5;
	clj_value t20 = clj_vector_from_array(a5, 2);
	(void)t19;
	(void)t18;
	if (t20 == CLJ_THROWN) {
	goto L2;
	}
	t12 = t20;
	}
	clj_c_leave(&S[7], &cc);
	clj_release(l1);
	clj_release(l2);
	clj_release(l3);
	return t12;
L2: ;
	clj_c_leave(&S[7], &cc);
L1: ;
	clj_release(l1);
	clj_release(l2);
	clj_release(l3);
	return CLJ_THROWN;
}

static clj_value clojure_walk_stringify_keys__0(void *ctx, const clj_value *args, size_t n) {
	const clj_fn *f = ctx;
	switch (n) {
	case 1: return clojure_walk_stringify_keys__0_a1(clj_from_ptr((void *)f), f->env, args, n);
	default: break;
	}
	return clj_c_arity_error(clj_from_ptr((void *)f), n);
}

static clj_value clojure_walk_stringify_keys__1_a1(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs) {
	(void)self; (void)captured; (void)args; (void)nargs;
	clj_cframe fr = {NULL, captured, 0, NULL};
	(void)fr;
	clj_value l0 = args[0];
	(void)l0;
	clj_ccall cc;
	if (!clj_c_enter(&S[8], &cc)) goto L1;
#line 34 "<embedded>/clojure/walk.clj"
	clj_value t0 = l0;
	clj_value a0[1] = {t0};
	(void)a0;
	clj_value t1;
	if (CLJC_GUARD(V[21], B[5])) {
	t1 = clj_map_p(t0);
	} else {
	t1 = clj_c_intrinsic_fallback(V[21], a0, 1);
	}
	(void)t0;
	if (t1 == CLJ_THROWN) {
	goto L2;
	}
	bool t2 = clj_truthy(t1);
	clj_release(t1);
	clj_value t3;
	if (t2) {
	clj_value t4 = K[20];
	clj_value t5 = fr.captured[0];
	clj_value t6 = l0;
	clj_value a1[3] = {t4, t5, t6};
	(void)a1;
	clj_cframe fr1 = {(clj_value *)a1, NULL, 0, NULL};
	(void)fr1;
	clj_value t7;
	{
	const clj_fusion_var *g1[3] = {F[0], F[1], F[2]};
	(void)g1;
	if (CLJC_FUSED(g1, 3)) {
	bool o8;
	clj_value t8 = clj_c_var_borrow(V[11], &o8);
	if (t8 == CLJ_THROWN) {
	goto L2;
	}
	clj_value t9 = fr1.slots[0];
	clj_value t10 = fr1.slots[2];
	bool o11;
	clj_value t11 = clj_c_var_borrow(V[6], &o11);
	if (t11 == CLJ_THROWN) {
	if (o8) clj_release(t8);
	goto L2;
	}
	clj_value t12 = fr1.slots[1];
	clj_value a4[1] = {t12};
	(void)a4;
	clj_value t13;
#ifdef CLJC_DIRECT_clojure_core_map_a1
	if (!CLJC_FN_clojure_core_map_a1) CLJC_FN_clojure_core_map_a1 = clj_compiled_symbol("clojure_core_map_a1");
	t13 = CLJC_FN_clojure_core_map_a1 ? CLJC_FN_clojure_core_map_a1(clj_var_root_relaxed(V[6]), NULL, a4, 1) : clj_c_invoke(t11, a4, 1);
#else
	t13 = clj_c_invoke(t11, a4, 1);
#endif
	(void)t12;
	if (o11) clj_release(t11);
	if (t13 == CLJ_THROWN) {
	if (o8) clj_release(t8);
	goto L2;
	}
	clj_value a3[1] = {t13};
	(void)a3;
	clj_value t14 = clj_vector_from_array(a3, 1);
	clj_release(t13);
	if (t14 == CLJ_THROWN) {
	if (o8) clj_release(t8);
	goto L2;
	}
	clj_value a2[3] = {t9, t10, t14};
	(void)a2;
	clj_value t15 = clj_c_invoke(t8, a2, 3);
	clj_release(t14);
	(void)t10;
	(void)t9;
	if (o8) clj_release(t8);
	if (t15 == CLJ_THROWN) {
	goto L2;
	}
	t7 = t15;
	} else {
	bool o16;
	clj_value t16 = clj_c_var_borrow(V[12], &o16);
	if (t16 == CLJ_THROWN) {
	goto L2;
	}
	clj_value t17 = fr1.slots[0];
	bool o18;
	clj_value t18 = clj_c_var_borrow(V[6], &o18);
	if (t18 == CLJ_THROWN) {
	if (o16) clj_release(t16);
	goto L2;
	}
	clj_value t19 = fr1.slots[1];
	clj_value t20 = fr1.slots[2];
	clj_value a6[2] = {t19, t20};
	(void)a6;
	clj_value t21;
#ifdef CLJC_DIRECT_clojure_core_map_a2
	if (!CLJC_FN_clojure_core_map_a2) CLJC_FN_clojure_core_map_a2 = clj_compiled_symbol("clojure_core_map_a2");
	t21 = CLJC_FN_clojure_core_map_a2 ? CLJC_FN_clojure_core_map_a2(clj_var_root_relaxed(V[6]), NULL, a6, 2) : clj_c_invoke(t18, a6, 2);
#else
	t21 = clj_c_invoke(t18, a6, 2);
#endif
	(void)t20;
	(void)t19;
	if (o18) clj_release(t18);
	if (t21 == CLJ_THROWN) {
	if (o16) clj_release(t16);
	goto L2;
	}
	clj_value a5[2] = {t17, t21};
	(void)a5;
	clj_value t22 = clj_c_invoke(t16, a5, 2);
	clj_release(t21);
	(void)t17;
	if (o16) clj_release(t16);
	if (t22 == CLJ_THROWN) {
	goto L2;
	}
	t7 = t22;
	}
	}
	(void)t6;
	(void)t5;
	(void)t4;
	t3 = t7;
	} else {
	clj_value t23 = clj_retain(l0);
	t3 = t23;
	}
	clj_c_leave(&S[8], &cc);
	return t3;
L2: ;
	clj_c_leave(&S[8], &cc);
L1: ;
	return CLJ_THROWN;
}

static clj_value clojure_walk_stringify_keys__1(void *ctx, const clj_value *args, size_t n) {
	const clj_fn *f = ctx;
	switch (n) {
	case 1: return clojure_walk_stringify_keys__1_a1(clj_from_ptr((void *)f), f->env, args, n);
	default: break;
	}
	return clj_c_arity_error(clj_from_ptr((void *)f), n);
}

clj_value clojure_walk_stringify_keys_a1(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs) {
	(void)self; (void)captured; (void)args; (void)nargs;
	clj_value s[2];
	clj_cframe fr = {s, captured, 0, NULL};
	(void)fr;
	clj_value l0 = args[0];
	(void)l0;
	for (uint32_t i = 1; i < 2; i++) s[i] = CLJ_NIL;
	clj_ccall cc;
	if (!clj_c_enter(&S[6], &cc)) goto L1;
#line 33 "<embedded>/clojure/walk.clj"
	clj_value t0 = clj_c_closure(CLJ_NIL, clojure_walk_stringify_keys__0, NULL, 0, 0x2, 1, 1);
	clj_c_set(&fr, 1, t0);
#line 34 "<embedded>/clojure/walk.clj"
	bool o1;
	clj_value t1 = clj_c_var_borrow(V[13], &o1);
	if (t1 == CLJ_THROWN) {
	goto L2;
	}
	clj_value c1[1] = {fr.slots[1]};
	clj_value t2 = clj_c_closure(CLJ_NIL, clojure_walk_stringify_keys__1, c1, 1, 0x2, 1, 1);
	clj_value t3 = l0;
	clj_value a0[2] = {t2, t3};
	(void)a0;
	clj_value t4;
#ifdef CLJC_DIRECT_clojure_walk_postwalk_a2
	if (!CLJC_FN_clojure_walk_postwalk_a2) CLJC_FN_clojure_walk_postwalk_a2 = clj_compiled_symbol("clojure_walk_postwalk_a2");
	t4 = CLJC_FN_clojure_walk_postwalk_a2 ? CLJC_FN_clojure_walk_postwalk_a2(clj_var_root_relaxed(V[13]), NULL, a0, 2) : clj_c_invoke(t1, a0, 2);
#else
	t4 = clj_c_invoke(t1, a0, 2);
#endif
	(void)t3;
	clj_release(t2);
	if (o1) clj_release(t1);
	if (t4 == CLJ_THROWN) {
	goto L2;
	}
	clj_c_leave(&S[6], &cc);
	clj_c_release_slots(&fr, 2);
	return t4;
L2: ;
	clj_c_leave(&S[6], &cc);
L1: ;
	clj_c_release_slots(&fr, 2);
	return CLJ_THROWN;
}

static clj_value clojure_walk_stringify_keys(void *ctx, const clj_value *args, size_t n) {
	const clj_fn *f = ctx;
	switch (n) {
	case 1: return clojure_walk_stringify_keys_a1(clj_from_ptr((void *)f), f->env, args, n);
	default: break;
	}
	return clj_c_arity_error(clj_from_ptr((void *)f), n);
}

static clj_value top_7(void) {
	clj_cframe fr = {NULL, NULL, 0, NULL};
	(void)fr;
	clj_eval_top_enter();
#line 30 "<embedded>/clojure/walk.clj"
	clj_value t0 = clj_c_closure(K[19], clojure_walk_stringify_keys, NULL, 0, 0x2, 1, 1);
	clj_var_bind_root(V[22], t0);
	clj_release(t0);
	clj_value t1 = clj_retain(K[21]);
	clj_value t2 = clj_c_def(V[22], t1, false, false);
	clj_release(t1);
	if (t2 == CLJ_THROWN) {
	goto L1;
	}
	clj_eval_top_leave();
	return t2;
L1: ;
	clj_eval_top_leave();
	return CLJ_THROWN;
}

static clj_value clojure_walk_prewalk_replace__0_a1(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs) {
	(void)self; (void)captured; (void)args; (void)nargs;
	clj_cframe fr = {NULL, captured, 0, NULL};
	(void)fr;
	clj_value l0 = args[0];
	(void)l0;
	clj_ccall cc;
	if (!clj_c_enter(&S[10], &cc)) goto L1;
#line 39 "<embedded>/clojure/walk.clj"
	clj_value t0 = fr.captured[0];
	clj_value t1 = l0;
	clj_value a0[2] = {t0, t1};
	(void)a0;
	clj_value t2;
	if (CLJC_GUARD(V[26], B[7])) {
	t2 = clj_contains_p(t0, t1);
	} else {
	t2 = clj_c_intrinsic_fallback(V[26], a0, 2);
	}
	(void)t1;
	(void)t0;
	if (t2 == CLJ_THROWN) {
	goto L2;
	}
	bool t3 = clj_truthy(t2);
	clj_release(t2);
	clj_value t4;
	if (t3) {
	clj_value t5 = fr.captured[0];
	clj_value t6 = l0;
	clj_value a1[1] = {t6};
	(void)a1;
	clj_value t7 = clj_c_invoke(t5, a1, 1);
	(void)t6;
	(void)t5;
	if (t7 == CLJ_THROWN) {
	goto L2;
	}
	t4 = t7;
	} else {
	clj_value t8 = clj_retain(l0);
	t4 = t8;
	}
	clj_c_leave(&S[10], &cc);
	return t4;
L2: ;
	clj_c_leave(&S[10], &cc);
L1: ;
	return CLJ_THROWN;
}

static clj_value clojure_walk_prewalk_replace__0(void *ctx, const clj_value *args, size_t n) {
	const clj_fn *f = ctx;
	switch (n) {
	case 1: return clojure_walk_prewalk_replace__0_a1(clj_from_ptr((void *)f), f->env, args, n);
	default: break;
	}
	return clj_c_arity_error(clj_from_ptr((void *)f), n);
}

clj_value clojure_walk_prewalk_replace_a2(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs) {
	(void)self; (void)captured; (void)args; (void)nargs;
	clj_value s[1];
	clj_cframe fr = {s, captured, 0, NULL};
	(void)fr;
	s[0] = args[0];
	clj_value l1 = args[1];
	(void)l1;
	clj_ccall cc;
	if (!clj_c_enter(&S[9], &cc)) goto L1;
#line 39 "<embedded>/clojure/walk.clj"
	bool o0;
	clj_value t0 = clj_c_var_borrow(V[15], &o0);
	if (t0 == CLJ_THROWN) {
	goto L2;
	}
	clj_value c1[1] = {fr.slots[0]};
	clj_value t1 = clj_c_closure(CLJ_NIL, clojure_walk_prewalk_replace__0, c1, 1, 0x2, 1, 1);
	clj_value t2 = l1;
	clj_value a0[2] = {t1, t2};
	(void)a0;
	clj_value t3;
#ifdef CLJC_DIRECT_clojure_walk_prewalk_a2
	if (!CLJC_FN_clojure_walk_prewalk_a2) CLJC_FN_clojure_walk_prewalk_a2 = clj_compiled_symbol("clojure_walk_prewalk_a2");
	t3 = CLJC_FN_clojure_walk_prewalk_a2 ? CLJC_FN_clojure_walk_prewalk_a2(clj_var_root_relaxed(V[15]), NULL, a0, 2) : clj_c_invoke(t0, a0, 2);
#else
	t3 = clj_c_invoke(t0, a0, 2);
#endif
	(void)t2;
	clj_release(t1);
	if (o0) clj_release(t0);
	if (t3 == CLJ_THROWN) {
	goto L2;
	}
	clj_c_leave(&S[9], &cc);
	clj_c_release_slots(&fr, 1);
	return t3;
L2: ;
	clj_c_leave(&S[9], &cc);
L1: ;
	clj_c_release_slots(&fr, 1);
	return CLJ_THROWN;
}

static clj_value clojure_walk_prewalk_replace(void *ctx, const clj_value *args, size_t n) {
	const clj_fn *f = ctx;
	switch (n) {
	case 2: return clojure_walk_prewalk_replace_a2(clj_from_ptr((void *)f), f->env, args, n);
	default: break;
	}
	return clj_c_arity_error(clj_from_ptr((void *)f), n);
}

static clj_value top_8(void) {
	clj_cframe fr = {NULL, NULL, 0, NULL};
	(void)fr;
	clj_eval_top_enter();
#line 36 "<embedded>/clojure/walk.clj"
	clj_value t0 = clj_c_closure(K[23], clojure_walk_prewalk_replace, NULL, 0, 0x4, 2, 2);
	clj_var_bind_root(V[25], t0);
	clj_release(t0);
	clj_value t1 = clj_retain(K[24]);
	clj_value t2 = clj_c_def(V[25], t1, false, false);
	clj_release(t1);
	if (t2 == CLJ_THROWN) {
	goto L1;
	}
	clj_eval_top_leave();
	return t2;
L1: ;
	clj_eval_top_leave();
	return CLJ_THROWN;
}

static clj_value clojure_walk_postwalk_replace__0_a1(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs) {
	(void)self; (void)captured; (void)args; (void)nargs;
	clj_cframe fr = {NULL, captured, 0, NULL};
	(void)fr;
	clj_value l0 = args[0];
	(void)l0;
	clj_ccall cc;
	if (!clj_c_enter(&S[12], &cc)) goto L1;
#line 44 "<embedded>/clojure/walk.clj"
	clj_value t0 = fr.captured[0];
	clj_value t1 = l0;
	clj_value a0[2] = {t0, t1};
	(void)a0;
	clj_value t2;
	if (CLJC_GUARD(V[26], B[7])) {
	t2 = clj_contains_p(t0, t1);
	} else {
	t2 = clj_c_intrinsic_fallback(V[26], a0, 2);
	}
	(void)t1;
	(void)t0;
	if (t2 == CLJ_THROWN) {
	goto L2;
	}
	bool t3 = clj_truthy(t2);
	clj_release(t2);
	clj_value t4;
	if (t3) {
	clj_value t5 = fr.captured[0];
	clj_value t6 = l0;
	clj_value a1[1] = {t6};
	(void)a1;
	clj_value t7 = clj_c_invoke(t5, a1, 1);
	(void)t6;
	(void)t5;
	if (t7 == CLJ_THROWN) {
	goto L2;
	}
	t4 = t7;
	} else {
	clj_value t8 = clj_retain(l0);
	t4 = t8;
	}
	clj_c_leave(&S[12], &cc);
	return t4;
L2: ;
	clj_c_leave(&S[12], &cc);
L1: ;
	return CLJ_THROWN;
}

static clj_value clojure_walk_postwalk_replace__0(void *ctx, const clj_value *args, size_t n) {
	const clj_fn *f = ctx;
	switch (n) {
	case 1: return clojure_walk_postwalk_replace__0_a1(clj_from_ptr((void *)f), f->env, args, n);
	default: break;
	}
	return clj_c_arity_error(clj_from_ptr((void *)f), n);
}

clj_value clojure_walk_postwalk_replace_a2(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs) {
	(void)self; (void)captured; (void)args; (void)nargs;
	clj_value s[1];
	clj_cframe fr = {s, captured, 0, NULL};
	(void)fr;
	s[0] = args[0];
	clj_value l1 = args[1];
	(void)l1;
	clj_ccall cc;
	if (!clj_c_enter(&S[11], &cc)) goto L1;
#line 44 "<embedded>/clojure/walk.clj"
	bool o0;
	clj_value t0 = clj_c_var_borrow(V[13], &o0);
	if (t0 == CLJ_THROWN) {
	goto L2;
	}
	clj_value c1[1] = {fr.slots[0]};
	clj_value t1 = clj_c_closure(CLJ_NIL, clojure_walk_postwalk_replace__0, c1, 1, 0x2, 1, 1);
	clj_value t2 = l1;
	clj_value a0[2] = {t1, t2};
	(void)a0;
	clj_value t3;
#ifdef CLJC_DIRECT_clojure_walk_postwalk_a2
	if (!CLJC_FN_clojure_walk_postwalk_a2) CLJC_FN_clojure_walk_postwalk_a2 = clj_compiled_symbol("clojure_walk_postwalk_a2");
	t3 = CLJC_FN_clojure_walk_postwalk_a2 ? CLJC_FN_clojure_walk_postwalk_a2(clj_var_root_relaxed(V[13]), NULL, a0, 2) : clj_c_invoke(t0, a0, 2);
#else
	t3 = clj_c_invoke(t0, a0, 2);
#endif
	(void)t2;
	clj_release(t1);
	if (o0) clj_release(t0);
	if (t3 == CLJ_THROWN) {
	goto L2;
	}
	clj_c_leave(&S[11], &cc);
	clj_c_release_slots(&fr, 1);
	return t3;
L2: ;
	clj_c_leave(&S[11], &cc);
L1: ;
	clj_c_release_slots(&fr, 1);
	return CLJ_THROWN;
}

static clj_value clojure_walk_postwalk_replace(void *ctx, const clj_value *args, size_t n) {
	const clj_fn *f = ctx;
	switch (n) {
	case 2: return clojure_walk_postwalk_replace_a2(clj_from_ptr((void *)f), f->env, args, n);
	default: break;
	}
	return clj_c_arity_error(clj_from_ptr((void *)f), n);
}

static clj_value top_9(void) {
	clj_cframe fr = {NULL, NULL, 0, NULL};
	(void)fr;
	clj_eval_top_enter();
#line 41 "<embedded>/clojure/walk.clj"
	clj_value t0 = clj_c_closure(K[26], clojure_walk_postwalk_replace, NULL, 0, 0x4, 2, 2);
	clj_var_bind_root(V[27], t0);
	clj_release(t0);
	clj_value t1 = clj_retain(K[27]);
	clj_value t2 = clj_c_def(V[27], t1, false, false);
	clj_release(t1);
	if (t2 == CLJ_THROWN) {
	goto L1;
	}
	clj_eval_top_leave();
	return t2;
L1: ;
	clj_eval_top_leave();
	return CLJ_THROWN;
}

static clj_value clojure_walk_macroexpand_all__0_a1(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs) {
	(void)self; (void)captured; (void)args; (void)nargs;
	clj_cframe fr = {NULL, captured, 0, NULL};
	(void)fr;
	clj_value l0 = args[0];
	(void)l0;
	clj_ccall cc;
	if (!clj_c_enter(&S[14], &cc)) goto L1;
#line 49 "<embedded>/clojure/walk.clj"
	clj_value t0 = l0;
	clj_value a0[1] = {t0};
	(void)a0;
	clj_value t1;
	if (CLJC_GUARD(V[7], B[1])) {
	t1 = clj_seq_p(t0);
	} else {
	t1 = clj_c_intrinsic_fallback(V[7], a0, 1);
	}
	(void)t0;
	if (t1 == CLJ_THROWN) {
	goto L2;
	}
	bool t2 = clj_truthy(t1);
	clj_release(t1);
	clj_value t3;
	if (t2) {
	bool o4;
	clj_value t4 = clj_c_var_borrow(V[29], &o4);
	if (t4 == CLJ_THROWN) {
	goto L2;
	}
	clj_value t5 = l0;
	clj_value a1[1] = {t5};
	(void)a1;
	clj_value t6 = clj_c_invoke(t4, a1, 1);
	(void)t5;
	if (o4) clj_release(t4);
	if (t6 == CLJ_THROWN) {
	goto L2;
	}
	t3 = t6;
	} else {
	clj_value t7 = clj_retain(l0);
	t3 = t7;
	}
	clj_c_leave(&S[14], &cc);
	return t3;
L2: ;
	clj_c_leave(&S[14], &cc);
L1: ;
	return CLJ_THROWN;
}

static clj_value clojure_walk_macroexpand_all__0(void *ctx, const clj_value *args, size_t n) {
	const clj_fn *f = ctx;
	switch (n) {
	case 1: return clojure_walk_macroexpand_all__0_a1(clj_from_ptr((void *)f), f->env, args, n);
	default: break;
	}
	return clj_c_arity_error(clj_from_ptr((void *)f), n);
}

clj_value clojure_walk_macroexpand_all_a1(clj_value self, const clj_value *captured, const clj_value *args, size_t nargs) {
	(void)self; (void)captured; (void)args; (void)nargs;
	clj_cframe fr = {NULL, captured, 0, NULL};
	(void)fr;
	clj_value l0 = args[0];
	(void)l0;
	clj_ccall cc;
	if (!clj_c_enter(&S[13], &cc)) goto L1;
#line 49 "<embedded>/clojure/walk.clj"
	bool o0;
	clj_value t0 = clj_c_var_borrow(V[15], &o0);
	if (t0 == CLJ_THROWN) {
	goto L2;
	}
	clj_value t1 = clj_c_closure(CLJ_NIL, clojure_walk_macroexpand_all__0, NULL, 0, 0x2, 1, 1);
	clj_value t2 = l0;
	clj_value a0[2] = {t1, t2};
	(void)a0;
	clj_value t3;
#ifdef CLJC_DIRECT_clojure_walk_prewalk_a2
	if (!CLJC_FN_clojure_walk_prewalk_a2) CLJC_FN_clojure_walk_prewalk_a2 = clj_compiled_symbol("clojure_walk_prewalk_a2");
	t3 = CLJC_FN_clojure_walk_prewalk_a2 ? CLJC_FN_clojure_walk_prewalk_a2(clj_var_root_relaxed(V[15]), NULL, a0, 2) : clj_c_invoke(t0, a0, 2);
#else
	t3 = clj_c_invoke(t0, a0, 2);
#endif
	(void)t2;
	clj_release(t1);
	if (o0) clj_release(t0);
	if (t3 == CLJ_THROWN) {
	goto L2;
	}
	clj_c_leave(&S[13], &cc);
	return t3;
L2: ;
	clj_c_leave(&S[13], &cc);
L1: ;
	return CLJ_THROWN;
}

static clj_value clojure_walk_macroexpand_all(void *ctx, const clj_value *args, size_t n) {
	const clj_fn *f = ctx;
	switch (n) {
	case 1: return clojure_walk_macroexpand_all_a1(clj_from_ptr((void *)f), f->env, args, n);
	default: break;
	}
	return clj_c_arity_error(clj_from_ptr((void *)f), n);
}

static clj_value top_10(void) {
	clj_cframe fr = {NULL, NULL, 0, NULL};
	(void)fr;
	clj_eval_top_enter();
#line 46 "<embedded>/clojure/walk.clj"
	clj_value t0 = clj_c_closure(K[29], clojure_walk_macroexpand_all, NULL, 0, 0x2, 1, 1);
	clj_var_bind_root(V[28], t0);
	clj_release(t0);
	clj_value t1 = clj_retain(K[30]);
	clj_value t2 = clj_c_def(V[28], t1, false, false);
	clj_release(t1);
	if (t2 == CLJ_THROWN) {
	goto L1;
	}
	clj_eval_top_leave();
	return t2;
L1: ;
	clj_eval_top_leave();
	return CLJ_THROWN;
}

static bool pools_filled;

static void unit_pools(void) {
	(void)K; (void)V; (void)B; (void)OP; (void)F; (void)S;
	pools_filled = true;
	V[0] = clj_c_var("clojure.core", "in-ns");
	V[1] = clj_c_var("clojure.core", "refer-clojure");
	V[2] = clj_c_var("clojure.walk", "walk");
	V[3] = clj_c_var("clojure.core", "list?");
	V[4] = clj_c_var("clojure.core", "apply");
	V[5] = clj_c_var("clojure.core", "list");
	V[6] = clj_c_var("clojure.core", "map");
	V[7] = clj_c_var("clojure.core", "seq?");
	V[8] = clj_c_var("clojure.core", "doall");
	V[9] = clj_c_var("clojure.core", "coll?");
	V[10] = clj_c_var("clojure.core", "empty");
	V[11] = clj_c_var("clojure.core", "fused-into*");
	V[12] = clj_c_var("clojure.core", "into");
	V[13] = clj_c_var("clojure.walk", "postwalk");
	V[14] = clj_c_var("clojure.core", "partial");
	V[15] = clj_c_var("clojure.walk", "prewalk");
	V[16] = clj_c_var("clojure.core", "identity");
	V[17] = clj_c_var("clojure.walk", "keywordize-keys");
	V[18] = clj_c_var("clojure.core", "nth");
	V[19] = clj_c_var("clojure.core", "string?");
	V[20] = clj_c_var("clojure.core", "keyword");
	V[21] = clj_c_var("clojure.core", "map?");
	V[22] = clj_c_var("clojure.walk", "stringify-keys");
	V[23] = clj_c_var("clojure.core", "keyword?");
	V[24] = clj_c_var("clojure.core", "name");
	V[25] = clj_c_var("clojure.walk", "prewalk-replace");
	V[26] = clj_c_var("clojure.core", "contains?");
	V[27] = clj_c_var("clojure.walk", "postwalk-replace");
	V[28] = clj_c_var("clojure.walk", "macroexpand-all");
	V[29] = clj_c_var("clojure.core", "macroexpand");
	K[0] = clj_c_const("\"<embedded>/clojure/walk.clj\"", 29);
	K[1] = clj_c_const("clojure.walk", 12);
	K[2] = clj_c_const("nil", 3);
	K[3] = clj_c_const("walk", 4);
	K[4] = clj_c_const("clojure.walk/walk", 17);
	K[5] = clj_c_const("{:ns clojure.walk, :file \"<embedded>/clojure/walk.clj\", :arglists ([inner outer form]), :doc \"Traverses form, applying inner to each element of a collection and outer to the result; outer to a leaf.\", :name walk, :line 5, :column 1}", 232);
	K[6] = clj_c_const("postwalk", 8);
	K[7] = clj_c_const("clojure.walk/postwalk", 21);
	K[8] = clj_c_const("{:ns clojure.walk, :file \"<embedded>/clojure/walk.clj\", :arglists ([f form]), :doc \"Performs a depth-first, post-order traversal of form, replacing each sub-form with (f sub-form).\", :name postwalk, :line 14, :column 1}", 219);
	K[9] = clj_c_const("prewalk", 7);
	K[10] = clj_c_const("clojure.walk/prewalk", 20);
	K[11] = clj_c_const("{:ns clojure.walk, :file \"<embedded>/clojure/walk.clj\", :arglists ([f form]), :doc \"Like postwalk, but does pre-order traversal.\", :name prewalk, :line 19, :column 1}", 166);
	K[12] = clj_c_const("keywordize-keys", 15);
	K[13] = clj_c_const("clojure.walk/keywordize-keys", 28);
	K[14] = clj_c_const("0", 1);
	K[15] = clj_c_const("1", 1);
	K[16] = clj_c_const("{}", 2);
	K[17] = clj_c_const("{:ns clojure.walk, :file \"<embedded>/clojure/walk.clj\", :arglists ([m]), :doc \"Recursively transforms all map keys from strings to keywords.\", :name keywordize-keys, :line 24, :column 1}", 186);
	K[18] = clj_c_const("stringify-keys", 14);
	K[19] = clj_c_const("clojure.walk/stringify-keys", 27);
	K[20] = clj_c_const("{}", 2);
	K[21] = clj_c_const("{:ns clojure.walk, :file \"<embedded>/clojure/walk.clj\", :arglists ([m]), :doc \"Recursively transforms all map keys from keywords to strings.\", :name stringify-keys, :line 30, :column 1}", 185);
	K[22] = clj_c_const("prewalk-replace", 15);
	K[23] = clj_c_const("clojure.walk/prewalk-replace", 28);
	K[24] = clj_c_const("{:ns clojure.walk, :file \"<embedded>/clojure/walk.clj\", :arglists ([smap form]), :doc \"Recursively transforms form by replacing keys in smap with their values, pre-order.\", :name prewalk-replace, :line 36, :column 1}", 216);
	K[25] = clj_c_const("postwalk-replace", 16);
	K[26] = clj_c_const("clojure.walk/postwalk-replace", 29);
	K[27] = clj_c_const("{:ns clojure.walk, :file \"<embedded>/clojure/walk.clj\", :arglists ([smap form]), :doc \"Recursively transforms form by replacing keys in smap with their values, post-order.\", :name postwalk-replace, :line 41, :column 1}", 218);
	K[28] = clj_c_const("macroexpand-all", 15);
	K[29] = clj_c_const("clojure.walk/macroexpand-all", 28);
	K[30] = clj_c_const("{:ns clojure.walk, :file \"<embedded>/clojure/walk.clj\", :arglists ([form]), :doc \"Recursively performs all possible macroexpansions in form.\", :name macroexpand-all, :line 46, :column 1}", 186);
	OP[0] = clj_c_intrinsic("clojure.core/list?", 1);
	B[0] = clj_intrinsic_builtin(OP[0]);
	OP[1] = clj_c_intrinsic("clojure.core/seq?", 1);
	B[1] = clj_intrinsic_builtin(OP[1]);
	OP[2] = clj_c_intrinsic("clojure.core/coll?", 1);
	B[2] = clj_intrinsic_builtin(OP[2]);
	OP[3] = clj_c_intrinsic("clojure.core/nth", 3);
	B[3] = clj_intrinsic_builtin(OP[3]);
	OP[4] = clj_c_intrinsic("clojure.core/string?", 1);
	B[4] = clj_intrinsic_builtin(OP[4]);
	OP[5] = clj_c_intrinsic("clojure.core/map?", 1);
	B[5] = clj_intrinsic_builtin(OP[5]);
	OP[6] = clj_c_intrinsic("clojure.core/keyword?", 1);
	B[6] = clj_intrinsic_builtin(OP[6]);
	OP[7] = clj_c_intrinsic("clojure.core/contains?", 2);
	B[7] = clj_intrinsic_builtin(OP[7]);
	F[0] = clj_c_fusion_var("clojure.core/into");
	F[1] = clj_c_fusion_var("clojure.core/map");
	F[2] = clj_c_fusion_var("clojure.core/fused-into*");
}

clj_value clj_compiled_lib_init_clojure_walk(void) {
	clj_value r;
	(void)r;
	if (!pools_filled) unit_pools();
#ifdef CLJ_CLOSED
	clj_compiled_register_symbol("clojure_walk_walk_a3", clojure_walk_walk_a3);
	clj_compiled_register_symbol("clojure_walk_postwalk_a2", clojure_walk_postwalk_a2);
	clj_compiled_register_symbol("clojure_walk_prewalk_a2", clojure_walk_prewalk_a2);
	clj_compiled_register_symbol("clojure_walk_keywordize_keys_a1", clojure_walk_keywordize_keys_a1);
	clj_compiled_register_symbol("clojure_walk_stringify_keys_a1", clojure_walk_stringify_keys_a1);
	clj_compiled_register_symbol("clojure_walk_prewalk_replace_a2", clojure_walk_prewalk_replace_a2);
	clj_compiled_register_symbol("clojure_walk_postwalk_replace_a2", clojure_walk_postwalk_replace_a2);
	clj_compiled_register_symbol("clojure_walk_macroexpand_all_a1", clojure_walk_macroexpand_all_a1);
#endif
	// form 1 at 3:1
	if (0) {
F1: ;
	if (!clj_load_form_failed(FILE_STR, 3, 1, CLJ_NIL)) goto fail;
	goto N1;
	}
	r = top_0();
	if (r == CLJ_THROWN) goto F1;
	clj_release(r);
	r = top_1();
	if (r == CLJ_THROWN) goto F1;
	clj_release(r);
	r = top_2();
	if (r == CLJ_THROWN) goto F1;
	clj_release(r);
N1: ;
	// form 2 at 5:1
	if (0) {
F2: ;
	if (!clj_load_form_failed(FILE_STR, 5, 1, K[3])) goto fail;
	goto N2;
	}
	clj_c_stub_init(&S[0], K[4], 5, 1);
	r = top_3();
	if (r == CLJ_THROWN) goto F2;
	clj_release(r);
N2: ;
	// form 3 at 14:1
	if (0) {
F3: ;
	if (!clj_load_form_failed(FILE_STR, 14, 1, K[6])) goto fail;
	goto N3;
	}
	clj_c_stub_init(&S[1], K[7], 14, 1);
	r = top_4();
	if (r == CLJ_THROWN) goto F3;
	clj_release(r);
N3: ;
	// form 4 at 19:1
	if (0) {
F4: ;
	if (!clj_load_form_failed(FILE_STR, 19, 1, K[9])) goto fail;
	goto N4;
	}
	clj_c_stub_init(&S[2], K[10], 19, 1);
	r = top_5();
	if (r == CLJ_THROWN) goto F4;
	clj_release(r);
N4: ;
	// form 5 at 24:1
	if (0) {
F5: ;
	if (!clj_load_form_failed(FILE_STR, 24, 1, K[12])) goto fail;
	goto N5;
	}
	clj_c_stub_init(&S[3], K[13], 24, 1);
	clj_c_stub_init(&S[4], CLJ_NIL, 27, 11);
	clj_c_stub_init(&S[5], CLJ_NIL, 28, 15);
	r = top_6();
	if (r == CLJ_THROWN) goto F5;
	clj_release(r);
N5: ;
	// form 6 at 30:1
	if (0) {
F6: ;
	if (!clj_load_form_failed(FILE_STR, 30, 1, K[18])) goto fail;
	goto N6;
	}
	clj_c_stub_init(&S[6], K[19], 30, 1);
	clj_c_stub_init(&S[7], CLJ_NIL, 33, 11);
	clj_c_stub_init(&S[8], CLJ_NIL, 34, 15);
	r = top_7();
	if (r == CLJ_THROWN) goto F6;
	clj_release(r);
N6: ;
	// form 7 at 36:1
	if (0) {
F7: ;
	if (!clj_load_form_failed(FILE_STR, 36, 1, K[22])) goto fail;
	goto N7;
	}
	clj_c_stub_init(&S[9], K[23], 36, 1);
	clj_c_stub_init(&S[10], CLJ_NIL, 39, 12);
	r = top_8();
	if (r == CLJ_THROWN) goto F7;
	clj_release(r);
N7: ;
	// form 8 at 41:1
	if (0) {
F8: ;
	if (!clj_load_form_failed(FILE_STR, 41, 1, K[25])) goto fail;
	goto N8;
	}
	clj_c_stub_init(&S[11], K[26], 41, 1);
	clj_c_stub_init(&S[12], CLJ_NIL, 44, 13);
	r = top_9();
	if (r == CLJ_THROWN) goto F8;
	clj_release(r);
N8: ;
	// form 9 at 46:1
	if (0) {
F9: ;
	if (!clj_load_form_failed(FILE_STR, 46, 1, K[28])) goto fail;
	goto N9;
	}
	clj_c_stub_init(&S[13], K[29], 46, 1);
	clj_c_stub_init(&S[14], CLJ_NIL, 49, 12);
	r = top_10();
	if (r == CLJ_THROWN) goto F9;
	clj_release(r);
N9: ;
	return CLJ_NIL;
fail:
	return CLJ_THROWN;
}
#else
typedef int cljc_unit_disabled;
#endif
