// Generated by clj-compile --core; do not edit.
#include "clj/compiled.h"

#ifdef CLJ_COMPILED_CORE
clj_value clj_compiled_lib_init_clojure_set(void);
clj_value clj_compiled_lib_init_clojure_string(void);
clj_value clj_compiled_lib_init_clojure_walk(void);
clj_value clj_compiled_lib_init_clojure_template(void);
clj_value clj_compiled_lib_init_clojure_test(void);
clj_value clj_compiled_lib_init_clojure_core_async(void);

void clj_compiled_libs_register(void) {
	clj_compiled_register("<embedded>/clojure/set.clj", clj_compiled_lib_init_clojure_set);
	clj_compiled_register("<embedded>/clojure/string.clj", clj_compiled_lib_init_clojure_string);
	clj_compiled_register("<embedded>/clojure/walk.clj", clj_compiled_lib_init_clojure_walk);
	clj_compiled_register("<embedded>/clojure/template.clj", clj_compiled_lib_init_clojure_template);
	clj_compiled_register("<embedded>/clojure/test.clj", clj_compiled_lib_init_clojure_test);
	clj_compiled_register("<embedded>/clojure/core/async.clj", clj_compiled_lib_init_clojure_core_async);
}
#else
typedef int cljc_libs_disabled;
#endif
