#!/bin/sh
# @ai-generated(guided)
# Regenerates Sources/CljCore/core_clj.inc from boot/core.clj and libs_clj.inc from boot/clojure/*.clj;
# run through `make boot` and commit all of them.
set -eu
cd "$(dirname "$0")/../Sources/CljCore"
{
	printf '// Generated by scripts/embed-core.sh from boot/core.clj; do not edit.\n'
	printf 'static const unsigned char core_clj[] = {\n'
	xxd -i < boot/core.clj
	printf '};\n'
	printf 'static const size_t core_clj_len = sizeof core_clj;\n'
} > core_clj.inc
{
	printf '// Generated by scripts/embed-core.sh from boot/clojure/*.clj; do not edit.\n'
	for f in boot/clojure/*.clj; do
		name=$(basename "$f" .clj)
		printf 'static const unsigned char lib_%s[] = {\n' "$name"
		xxd -i < "$f"
		printf '};\n'
	done
	printf 'static const struct {\n\tconst char          *name;\n\tconst unsigned char *bytes;\n\tsize_t               len;\n} embedded_libs[] = {\n'
	for f in boot/clojure/*.clj; do
		name=$(basename "$f" .clj)
		printf '\t{"clojure/%s", lib_%s, sizeof lib_%s},\n' "$name" "$name" "$name"
	done
	printf '};\n'
} > libs_clj.inc
