#!/bin/sh
# @ai-generated(guided)
# Regenerates Sources/CljCore/core_clj.inc from boot/core.clj; run through `make boot` and commit both.
set -eu
cd "$(dirname "$0")/../Sources/CljCore"
{
	printf '// Generated by scripts/embed-core.sh from boot/core.clj; do not edit.\n'
	printf 'static const unsigned char core_clj[] = {\n'
	xxd -i < boot/core.clj
	printf '};\n'
	printf 'static const size_t core_clj_len = sizeof core_clj;\n'
} > core_clj.inc
