#!/usr/bin/env python3
# @ai-generated(solo)
"""Collect every open ([ ]) and partly done ([~]) item of docs/design/ and docs/notes/ into docs/open.md.

Usage: scripts/open-items.py [--check]
--check exits 1 when docs/open.md differs from what the marks give, without writing it.
"""

import glob
import os
import re
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
OUT = 'docs/open.md'
ITEM = re.compile(r'^( *)(- |(\d+)\. )\[([ x~])\] (.*)$')
# The clause that names what is still open, in either document's language.
OPEN = re.compile(r'[Нн]е сделан|[Нн]е взят|[Оо]стал(ся|ись|ось|ась)|следующий (шаг|триггер)|[Tt]rigger|'
                  r'[Nn]ot done|[Dd]eferred|[Nn]ot yet|Fix:')


def clip(s, n):
	s = s.strip()
	if len(s) <= n:
		return s
	cut = s[:n].rsplit(' ', 1)[0]
	return cut + ' …'


def label(text, number):
	m = re.match(r'(\*\*.+?\*\*|\*[^*]+?\*)', text)
	head = m.group(1).strip('*').strip() if m else clip(re.split(r'(?<=\.)\s', text, 1)[0], 90)
	head = head.rstrip(':')
	return f'{number}. {head}' if number and not head.startswith(number) else head


def open_clause(text):
	for sentence in re.split(r'(?<=[.;])\s+', text):
		m = OPEN.search(sentence)
		if m:
			if len(sentence) > 220 and m.start() > 80:
				sentence = '… ' + sentence[m.start():]
			return clip(sentence, 220).rstrip(';:')
	return ''


def items(path):
	lines = open(path, encoding='utf-8').read().split('\n')
	title = next(l.lstrip('#').strip() for l in lines if l.startswith('#'))
	found = []
	number = None
	for i, line in enumerate(lines):
		m = ITEM.match(line)
		if not m:
			continue
		indent = len(m.group(1))
		if m.group(3) and indent == 0:
			number = m.group(3)
		body = [m.group(5)]
		for nxt in lines[i + 1:]:
			if ITEM.match(nxt) or nxt.startswith('#'):
				break
			if nxt.strip() and len(nxt) - len(nxt.lstrip(' ')) <= indent:
				break
			body.append(nxt.strip())
		text = ' '.join(b for b in body if b)
		if m.group(4) == 'x':
			continue
		own = m.group(3) if m.group(3) else (number if indent > 0 else None)
		found.append((m.group(4), label(text, own), open_clause(text)))
	return title, found


def render():
	out = []
	total = {' ': 0, '~': 0}
	for part, heading in (('design', 'Design'), ('notes', 'Engineering notes')):
		out += [f'## {heading}', '']
		for path in sorted(glob.glob(os.path.join(ROOT, 'docs', part, '*.md'))):
			title, found = items(path)
			if not found:
				continue
			out.append(f'### [{title}]({part}/{os.path.basename(path)})')
			out.append('')
			for mark, lab, clause in found:
				total[mark] += 1
				out.append(f'- [{mark}] {lab}' + (f' — {clause}' if clause and clause not in lab else ''))
			out.append('')
	head = ['# Open items', '',
	        'Generated by `make open-items` (`scripts/open-items.py`) from the marks in docs/design/ and docs/notes/;',
	        'edit the marks there, not this file. `[ ]` open, `[~]` partly done (the item names what is left).',
	        'Each line is the item\'s label and the sentence that names the open part; grep the label in the linked',
	        f'file. {total[" "]} open, {total["~"]} partly done.', '']
	return '\n'.join(head + out).rstrip('\n') + '\n'


def main():
	text = render()
	path = os.path.join(ROOT, OUT)
	if '--check' in sys.argv[1:]:
		current = open(path, encoding='utf-8').read() if os.path.exists(path) else ''
		if current != text:
			print(f'open-items: {OUT} is stale; run make open-items and commit it with the marks it reflects')
			sys.exit(1)
		print(f'open-items: {OUT} matches the marks')
		return
	open(path, 'w', encoding='utf-8').write(text)


main()
